# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_lesson_content.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(552, 780)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame = QtWidgets.QFrame(Form)
        self.top_frame.setMinimumSize(QtCore.QSize(530, 90))
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 90))
        self.top_frame.setStyleSheet("background-color: rgb(43, 72, 101);\n"
"border-radius: 20px;")
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_heading = QtWidgets.QLabel(self.top_frame)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_heading.setFont(font)
        self.lbl_heading.setStyleSheet("color: rgb(143, 227, 207);")
        self.lbl_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_heading.setObjectName("lbl_heading")
        self.horizontalLayout.addWidget(self.lbl_heading)
        self.verticalLayout.addWidget(self.top_frame)
        self.middle_frame = QtWidgets.QFrame(Form)
        self.middle_frame.setMinimumSize(QtCore.QSize(530, 560))
        self.middle_frame.setStyleSheet("background-color: rgb(32, 94, 115);\n"
"border-radius: 20px;")
        self.middle_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.middle_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middle_frame.setObjectName("middle_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.middle_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.middle_frame)
        self.frame.setMinimumSize(QtCore.QSize(491, 71))
        self.frame.setMaximumSize(QtCore.QSize(491, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_submit_2 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_submit_2.sizePolicy().hasHeightForWidth())
        self.btn_submit_2.setSizePolicy(sizePolicy)
        self.btn_submit_2.setMinimumSize(QtCore.QSize(171, 50))
        self.btn_submit_2.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        self.btn_submit_2.setFont(font)
        self.btn_submit_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_submit_2.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(43, 72, 101);\n"
"border-radius: 10px;\n"
"background-color:  #002B5B;\n"
"color: rgb(137, 218, 199)\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(43, 72, 101);\n"
"border: 3px solid rgb(0, 43, 91); \n"
"}")
        self.btn_submit_2.setFlat(True)
        self.btn_submit_2.setObjectName("btn_submit_2")
        self.horizontalLayout_2.addWidget(self.btn_submit_2)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(137, 218, 199);\n"
"padding-left: 10px;\n"
"border: 3px solid rgb(43, 72, 101);")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.middle_frame)
        self.frame_2.setMinimumSize(QtCore.QSize(491, 71))
        self.frame_2.setMaximumSize(QtCore.QSize(491, 72))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input_age = QtWidgets.QLineEdit(self.frame_2)
        self.input_age.setMinimumSize(QtCore.QSize(330, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(11)
        self.input_age.setFont(font)
        self.input_age.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"border: 2px solid rgb(101, 161, 146);\n"
"padding-left: 15px;\n"
"border-radius: 10px;\n"
"color: rgb(43, 72, 101);")
        self.input_age.setObjectName("input_age")
        self.horizontalLayout_3.addWidget(self.input_age)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.middle_frame)
        self.frame_3.setMinimumSize(QtCore.QSize(493, 180))
        self.frame_3.setMaximumSize(QtCore.QSize(493, 180))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.input_guardian = QtWidgets.QLineEdit(self.frame_3)
        self.input_guardian.setGeometry(QtCore.QRect(11, 35, 471, 141))
        self.input_guardian.setMinimumSize(QtCore.QSize(471, 141))
        self.input_guardian.setMaximumSize(QtCore.QSize(471, 141))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(11)
        self.input_guardian.setFont(font)
        self.input_guardian.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"border: 2px solid rgb(101, 161, 146);\n"
"padding-left: 15px;\n"
"padding-top: 11px;\n"
"border-radius: 10px;\n"
"color: rgb(43, 72, 101);")
        self.input_guardian.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.input_guardian.setObjectName("input_guardian")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.middle_frame)
        self.frame_5.setMinimumSize(QtCore.QSize(491, 142))
        self.frame_5.setMaximumSize(QtCore.QSize(491, 142))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(137, 218, 199)")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setMinimumSize(QtCore.QSize(469, 72))
        self.frame_4.setMaximumSize(QtCore.QSize(469, 72))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_submit_3 = QtWidgets.QPushButton(self.frame_4)
        self.btn_submit_3.setMinimumSize(QtCore.QSize(161, 50))
        self.btn_submit_3.setMaximumSize(QtCore.QSize(161, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(10)
        self.btn_submit_3.setFont(font)
        self.btn_submit_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_submit_3.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(43, 72, 101);\n"
"border-radius: 10px;\n"
"background-color:  #002B5B;\n"
"color: rgb(137, 218, 199)\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(43, 72, 101);\n"
"border: 3px solid rgb(0, 43, 91); \n"
"}")
        self.btn_submit_3.setFlat(True)
        self.btn_submit_3.setObjectName("btn_submit_3")
        self.horizontalLayout_4.addWidget(self.btn_submit_3)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setMinimumSize(QtCore.QSize(81, 45))
        self.label_5.setMaximumSize(QtCore.QSize(81, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(137, 218, 199);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.btn_submit_4 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_submit_4.sizePolicy().hasHeightForWidth())
        self.btn_submit_4.setSizePolicy(sizePolicy)
        self.btn_submit_4.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_submit_4.setMaximumSize(QtCore.QSize(161, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(10)
        self.btn_submit_4.setFont(font)
        self.btn_submit_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_submit_4.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(43, 72, 101);\n"
"border-radius: 10px;\n"
"background-color:  #002B5B;\n"
"color: rgb(137, 218, 199)\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(43, 72, 101);\n"
"border: 3px solid rgb(0, 43, 91); \n"
"}")
        self.btn_submit_4.setFlat(True)
        self.btn_submit_4.setObjectName("btn_submit_4")
        self.horizontalLayout_4.addWidget(self.btn_submit_4)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.btn_submit = QtWidgets.QPushButton(self.middle_frame)
        self.btn_submit.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        self.btn_submit.setFont(font)
        self.btn_submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_submit.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(43, 72, 101);\n"
"border-radius: 10px;\n"
"background-color:  #002B5B;\n"
"color: rgb(137, 218, 199)\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: rgb(43, 72, 101);\n"
"border: 3px solid rgb(0, 43, 91); \n"
"}")
        self.btn_submit.setFlat(True)
        self.btn_submit.setObjectName("btn_submit")
        self.verticalLayout_2.addWidget(self.btn_submit)
        self.verticalLayout.addWidget(self.middle_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_heading.setText(_translate("Form", "লেসনের কন্টেন্ট যুক্ত করুন"))
        self.btn_submit_2.setText(_translate("Form", "ছবি নির্বাচন করুন"))
        self.btn_submit_2.setShortcut(_translate("Form", "Return"))
        self.label.setText(_translate("Form", "ছবির নাম"))
        self.input_age.setPlaceholderText(_translate("Form", "পাঠ্যের বিষয় "))
        self.input_guardian.setPlaceholderText(_translate("Form", "পাঠ বিবরণী"))
        self.label_4.setText(_translate("Form", "অডিও যুক্ত করুন"))
        self.btn_submit_3.setText(_translate("Form", "অডিও নির্বাচন করুন"))
        self.btn_submit_3.setShortcut(_translate("Form", "Return"))
        self.label_5.setText(_translate("Form", "অথবা"))
        self.btn_submit_4.setText(_translate("Form", "অডিও রেকর্ড করুন"))
        self.btn_submit_4.setShortcut(_translate("Form", "Return"))
        self.btn_submit.setText(_translate("Form", "লেসন তৈরি করুন "))
        self.btn_submit.setShortcut(_translate("Form", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
