# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\lesson_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1309, 845)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1305, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setStyleSheet("background-color: rgb(0, 43, 91);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_menu_frame = QtWidgets.QFrame(self.main_frame)
        self.left_menu_frame.setMinimumSize(QtCore.QSize(225, 780))
        self.left_menu_frame.setMaximumSize(QtCore.QSize(225, 16777215))
        self.left_menu_frame.setStyleSheet("")
        self.left_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_frame.setObjectName("left_menu_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_menu_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.left_top_frame = QtWidgets.QFrame(self.left_menu_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_top_frame.sizePolicy().hasHeightForWidth())
        self.left_top_frame.setSizePolicy(sizePolicy)
        self.left_top_frame.setMinimumSize(QtCore.QSize(225, 75))
        self.left_top_frame.setMaximumSize(QtCore.QSize(275, 75))
        self.left_top_frame.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"border-top-left-radius: 15px;\n"
"border-top-right-radius: 15px;")
        self.left_top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_top_frame.setObjectName("left_top_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.left_top_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_back_to_home = QtWidgets.QPushButton(self.left_top_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back_to_home.sizePolicy().hasHeightForWidth())
        self.btn_back_to_home.setSizePolicy(sizePolicy)
        self.btn_back_to_home.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_back_to_home.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_back_to_home.setBaseSize(QtCore.QSize(0, 4))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_back_to_home.setFont(font)
        self.btn_back_to_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_back_to_home.setMouseTracking(True)
        self.btn_back_to_home.setStyleSheet("QPushButton {\n"
"    background-color: rgb(36, 105, 127) ;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(49, 146, 175);\n"
"    border-radius: 15px;\n"
"}")
        self.btn_back_to_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../Images/back_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back_to_home.setIcon(icon)
        self.btn_back_to_home.setIconSize(QtCore.QSize(200, 200))
        self.btn_back_to_home.setAutoDefault(False)
        self.btn_back_to_home.setDefault(False)
        self.btn_back_to_home.setFlat(False)
        self.btn_back_to_home.setObjectName("btn_back_to_home")
        self.horizontalLayout.addWidget(self.btn_back_to_home)
        self.lbl_left_heading = QtWidgets.QLabel(self.left_top_frame)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(23)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_left_heading.setFont(font)
        self.lbl_left_heading.setStyleSheet("color: rgb(0, 43, 91);")
        self.lbl_left_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_left_heading.setObjectName("lbl_left_heading")
        self.horizontalLayout.addWidget(self.lbl_left_heading)
        self.verticalLayout.addWidget(self.left_top_frame)
        self.left_center_frame = QtWidgets.QFrame(self.left_menu_frame)
        self.left_center_frame.setMinimumSize(QtCore.QSize(225, 530))
        self.left_center_frame.setMaximumSize(QtCore.QSize(275, 16777215))
        self.left_center_frame.setStyleSheet("background-color: rgb(137, 218, 199);")
        self.left_center_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_center_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_center_frame.setObjectName("left_center_frame")
        self.verticalLayout.addWidget(self.left_center_frame)
        self.left_bottom_frame = QtWidgets.QFrame(self.left_menu_frame)
        self.left_bottom_frame.setMinimumSize(QtCore.QSize(225, 100))
        self.left_bottom_frame.setMaximumSize(QtCore.QSize(275, 100))
        self.left_bottom_frame.setStyleSheet("background-color: rgb(143, 227, 207);\n"
"border-bottom-left-radius: 15px;\n"
"border-bottom-right-radius: 15px;")
        self.left_bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_bottom_frame.setObjectName("left_bottom_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.left_bottom_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(53, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bottom_logo = QtWidgets.QLabel(self.left_bottom_frame)
        self.bottom_logo.setMinimumSize(QtCore.QSize(127, 90))
        self.bottom_logo.setMaximumSize(QtCore.QSize(140, 90))
        self.bottom_logo.setStyleSheet("")
        self.bottom_logo.setText("")
        self.bottom_logo.setPixmap(QtGui.QPixmap(".\\../Images/bottom_banner.png"))
        self.bottom_logo.setObjectName("bottom_logo")
        self.horizontalLayout_3.addWidget(self.bottom_logo)
        spacerItem1 = QtWidgets.QSpacerItem(51, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.left_bottom_frame)
        self.horizontalLayout_2.addWidget(self.left_menu_frame)
        self.right_menu_frame = QtWidgets.QFrame(self.main_frame)
        self.right_menu_frame.setMinimumSize(QtCore.QSize(950, 780))
        self.right_menu_frame.setStyleSheet("background-color: rgb(36, 105, 127);\n"
"border-radius: 20px;")
        self.right_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_menu_frame.setObjectName("right_menu_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_menu_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.right_head_frame = QtWidgets.QFrame(self.right_menu_frame)
        self.right_head_frame.setMinimumSize(QtCore.QSize(950, 95))
        self.right_head_frame.setMaximumSize(QtCore.QSize(16777215, 95))
        self.right_head_frame.setStyleSheet("")
        self.right_head_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_head_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_head_frame.setObjectName("right_head_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.right_head_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_prev_lesson = QtWidgets.QPushButton(self.right_head_frame)
        self.btn_prev_lesson.setMaximumSize(QtCore.QSize(90, 80))
        self.btn_prev_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_prev_lesson.setStyleSheet("QPushButton {\n"
"    background-color: #2B4865 #256D85;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(46, 137, 165);\n"
"    border-top-left-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"}")
        self.btn_prev_lesson.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../Images/backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev_lesson.setIcon(icon1)
        self.btn_prev_lesson.setIconSize(QtCore.QSize(150, 150))
        self.btn_prev_lesson.setObjectName("btn_prev_lesson")
        self.horizontalLayout_4.addWidget(self.btn_prev_lesson)
        self.lbl_lesson_heading = QtWidgets.QLabel(self.right_head_frame)
        self.lbl_lesson_heading.setMinimumSize(QtCore.QSize(660, 0))
        self.lbl_lesson_heading.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri")
        font.setPointSize(23)
        self.lbl_lesson_heading.setFont(font)
        self.lbl_lesson_heading.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"border-radius: 15px;")
        self.lbl_lesson_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lesson_heading.setObjectName("lbl_lesson_heading")
        self.horizontalLayout_4.addWidget(self.lbl_lesson_heading)
        self.btn_next_lesson = QtWidgets.QPushButton(self.right_head_frame)
        self.btn_next_lesson.setMaximumSize(QtCore.QSize(90, 80))
        self.btn_next_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_next_lesson.setStyleSheet("QPushButton {\n"
"    background-color: #2B4865 #256D85;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color:  rgb(46, 137, 165);\n"
"    border-top-right-radius: 15px;\n"
"    border-bottom-right-radius: 15px;\n"
"}")
        self.btn_next_lesson.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\../Images/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next_lesson.setIcon(icon2)
        self.btn_next_lesson.setIconSize(QtCore.QSize(150, 150))
        self.btn_next_lesson.setObjectName("btn_next_lesson")
        self.horizontalLayout_4.addWidget(self.btn_next_lesson)
        self.verticalLayout_2.addWidget(self.right_head_frame)
        self.right_body_frame = QtWidgets.QFrame(self.right_menu_frame)
        self.right_body_frame.setMinimumSize(QtCore.QSize(1031, 610))
        self.right_body_frame.setStyleSheet("")
        self.right_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_body_frame.setObjectName("right_body_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.right_body_frame)
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_add_picture = QtWidgets.QLabel(self.right_body_frame)
        self.lbl_add_picture.setStyleSheet("border: 3px solid  rgb(137, 218, 199);")
        self.lbl_add_picture.setText("")
        self.lbl_add_picture.setObjectName("lbl_add_picture")
        self.horizontalLayout_5.addWidget(self.lbl_add_picture)
        self.lbl_photo_description = QtWidgets.QLabel(self.right_body_frame)
        self.lbl_photo_description.setMinimumSize(QtCore.QSize(300, 606))
        self.lbl_photo_description.setMaximumSize(QtCore.QSize(350, 16777215))
        self.lbl_photo_description.setStyleSheet("border: 3px solid rgb(137, 218, 199)")
        self.lbl_photo_description.setText("")
        self.lbl_photo_description.setObjectName("lbl_photo_description")
        self.horizontalLayout_5.addWidget(self.lbl_photo_description)
        self.verticalLayout_2.addWidget(self.right_body_frame)
        self.right_bottom_frame = QtWidgets.QFrame(self.right_menu_frame)
        self.right_bottom_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.right_bottom_frame.setStyleSheet("")
        self.right_bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_bottom_frame.setObjectName("right_bottom_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.right_bottom_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_create_new_lesson = QtWidgets.QPushButton(self.right_bottom_frame)
        self.btn_create_new_lesson.setMinimumSize(QtCore.QSize(300, 65))
        self.btn_create_new_lesson.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_create_new_lesson.setFont(font)
        self.btn_create_new_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_create_new_lesson.setStyleSheet("QPushButton {\n"
"background-color: rgb(160, 253, 230);\n"
"color:  #256D85 ;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    \n"
"    background-color: rgb(143, 227, 207);\n"
"    color: #2B4865;\n"
"\n"
"}")
        self.btn_create_new_lesson.setObjectName("btn_create_new_lesson")
        self.horizontalLayout_6.addWidget(self.btn_create_new_lesson)
        self.verticalLayout_2.addWidget(self.right_bottom_frame)
        self.horizontalLayout_2.addWidget(self.right_menu_frame)
        self.horizontalLayout_7.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_left_heading.setText(_translate("MainWindow", "পাঠসমূহ "))
        self.lbl_lesson_heading.setText(_translate("MainWindow", "পাঠ ১"))
        self.btn_create_new_lesson.setText(_translate("MainWindow", "নতুন লেসন তৈরি করুন"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
