# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Frontend\PyQt_UI\Lesson_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 882)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 882))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame = QtWidgets.QFrame(self.centralwidget)
        self.top_frame.setMinimumSize(QtCore.QSize(1180, 80))
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.top_frame.setStyleSheet("background-color: #2B4865;\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;")
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_back_to_home = QtWidgets.QPushButton(self.top_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back_to_home.sizePolicy().hasHeightForWidth())
        self.btn_back_to_home.setSizePolicy(sizePolicy)
        self.btn_back_to_home.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_back_to_home.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_back_to_home.setBaseSize(QtCore.QSize(0, 4))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_back_to_home.setFont(font)
        self.btn_back_to_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_back_to_home.setMouseTracking(True)
        self.btn_back_to_home.setStyleSheet("QPushButton {\n"
"    background-color: #2B4865 #256D85;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color:  #256D85;\n"
"    border-radius: 30px;\n"
"}")
        self.btn_back_to_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/back_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back_to_home.setIcon(icon)
        self.btn_back_to_home.setIconSize(QtCore.QSize(200, 200))
        self.btn_back_to_home.setAutoDefault(False)
        self.btn_back_to_home.setDefault(False)
        self.btn_back_to_home.setFlat(False)
        self.btn_back_to_home.setObjectName("btn_back_to_home")
        self.horizontalLayout.addWidget(self.btn_back_to_home)
        self.lbl_headline = QtWidgets.QLabel(self.top_frame)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(27)
        self.lbl_headline.setFont(font)
        self.lbl_headline.setStyleSheet("color: #8FE3CF")
        self.lbl_headline.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_headline.setObjectName("lbl_headline")
        self.horizontalLayout.addWidget(self.lbl_headline)
        self.verticalLayout.addWidget(self.top_frame)
        self.mid_frame = QtWidgets.QFrame(self.centralwidget)
        self.mid_frame.setMinimumSize(QtCore.QSize(1180, 610))
        self.mid_frame.setStyleSheet("\n"
"background-color:rgb(36, 105, 127);")
        self.mid_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mid_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mid_frame.setObjectName("mid_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.mid_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.bottom_top_frame = QtWidgets.QFrame(self.mid_frame)
        self.bottom_top_frame.setMinimumSize(QtCore.QSize(0, 60))
        self.bottom_top_frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.bottom_top_frame.setStyleSheet("background-color: rgb(29, 88, 105);\n"
"color: rgb(137, 218, 199);\n"
"border-radius: 20px;")
        self.bottom_top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_top_frame.setObjectName("bottom_top_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottom_top_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(141, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lbl_category = QtWidgets.QLabel(self.bottom_top_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_category.setFont(font)
        self.lbl_category.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_category.setObjectName("lbl_category")
        self.horizontalLayout_2.addWidget(self.lbl_category)
        self.cmb_category = QtWidgets.QComboBox(self.bottom_top_frame)
        self.cmb_category.setMinimumSize(QtCore.QSize(280, 40))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cmb_category.setFont(font)
        self.cmb_category.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"padding-left: 15px;\n"
"border-radius: 10px;\n"
"color: rgb(43, 72, 101);")
        self.cmb_category.setObjectName("cmb_category")
        self.cmb_category.addItem("")
        self.cmb_category.addItem("")
        self.cmb_category.addItem("")
        self.cmb_category.addItem("")
        self.cmb_category.addItem("")
        self.horizontalLayout_2.addWidget(self.cmb_category)
        spacerItem1 = QtWidgets.QSpacerItem(143, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lbl_lessons = QtWidgets.QLabel(self.bottom_top_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_lessons.setFont(font)
        self.lbl_lessons.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lessons.setObjectName("lbl_lessons")
        self.horizontalLayout_2.addWidget(self.lbl_lessons)
        self.cmb_lessons = QtWidgets.QComboBox(self.bottom_top_frame)
        self.cmb_lessons.setMinimumSize(QtCore.QSize(280, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cmb_lessons.setFont(font)
        self.cmb_lessons.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"border-radius: 12px;\n"
"color: rgb(0, 43, 91);\n"
"padding-left: 10px;")
        self.cmb_lessons.setObjectName("cmb_lessons")
        self.cmb_lessons.addItem("")
        self.horizontalLayout_2.addWidget(self.cmb_lessons)
        spacerItem2 = QtWidgets.QSpacerItem(141, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addWidget(self.bottom_top_frame, 0, 0, 1, 3)
        self.left_btn_frame = QtWidgets.QFrame(self.mid_frame)
        self.left_btn_frame.setMinimumSize(QtCore.QSize(60, 629))
        self.left_btn_frame.setMaximumSize(QtCore.QSize(60, 16777215))
        self.left_btn_frame.setStyleSheet("")
        self.left_btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_btn_frame.setObjectName("left_btn_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_btn_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_left = QtWidgets.QPushButton(self.left_btn_frame)
        self.btn_left.setMinimumSize(QtCore.QSize(60, 629))
        self.btn_left.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_left.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_left.setStyleSheet("QPushButton {background-color: rgb(30, 90, 108); border-radius: 20px;}\n"
"\n"
"QPushButton::hover  {\n"
"    background-color: rgb(20, 62, 74);\n"
"}\n"
"")
        self.btn_left.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_left.setIcon(icon1)
        self.btn_left.setIconSize(QtCore.QSize(100, 100))
        self.btn_left.setObjectName("btn_left")
        self.verticalLayout_3.addWidget(self.btn_left)
        self.gridLayout.addWidget(self.left_btn_frame, 1, 0, 1, 1)
        self.middle_content_frame = QtWidgets.QFrame(self.mid_frame)
        self.middle_content_frame.setStyleSheet("background-color: rgb(30, 90, 108);\n"
"border-radius: 20px;")
        self.middle_content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.middle_content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middle_content_frame.setObjectName("middle_content_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.middle_content_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_image = QtWidgets.QLabel(self.middle_content_frame)
        self.lbl_image.setMinimumSize(QtCore.QSize(600, 571))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lbl_image.setFont(font)
        self.lbl_image.setStyleSheet("border: 3px dotted  rgb(137, 218, 199);\n"
"color: rgb(137, 218, 199);")
        self.lbl_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image.setObjectName("lbl_image")
        self.horizontalLayout_7.addWidget(self.lbl_image)
        self.lbl_image_text = QtWidgets.QLabel(self.middle_content_frame)
        self.lbl_image_text.setMinimumSize(QtCore.QSize(390, 300))
        self.lbl_image_text.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lbl_image_text.setFont(font)
        self.lbl_image_text.setStyleSheet("border: 3px dotted  rgb(137, 218, 199);\n"
"color: rgb(137, 218, 199);")
        self.lbl_image_text.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image_text.setWordWrap(True)
        self.lbl_image_text.setObjectName("lbl_image_text")
        self.horizontalLayout_7.addWidget(self.lbl_image_text)
        self.gridLayout.addWidget(self.middle_content_frame, 1, 1, 1, 1)
        self.right_btn_frame = QtWidgets.QFrame(self.mid_frame)
        self.right_btn_frame.setMinimumSize(QtCore.QSize(60, 629))
        self.right_btn_frame.setMaximumSize(QtCore.QSize(60, 16777215))
        self.right_btn_frame.setStyleSheet("")
        self.right_btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_btn_frame.setObjectName("right_btn_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right_btn_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_right = QtWidgets.QPushButton(self.right_btn_frame)
        self.btn_right.setMinimumSize(QtCore.QSize(60, 629))
        self.btn_right.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_right.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_right.setStyleSheet("QPushButton {background-color: rgb(30, 90, 108); border-radius: 20px;}\n"
"\n"
"QPushButton::hover  {\n"
"    background-color: rgb(20, 62, 74);\n"
"}\n"
"")
        self.btn_right.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_right.setIcon(icon2)
        self.btn_right.setIconSize(QtCore.QSize(100, 100))
        self.btn_right.setObjectName("btn_right")
        self.verticalLayout_4.addWidget(self.btn_right)
        self.gridLayout.addWidget(self.right_btn_frame, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.mid_frame)
        self.bottom_frame = QtWidgets.QFrame(self.centralwidget)
        self.bottom_frame.setMinimumSize(QtCore.QSize(1180, 70))
        self.bottom_frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.bottom_frame.setStyleSheet("background-color: rgb(42, 70, 98);\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;")
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btn_add_new_lessons = QtWidgets.QPushButton(self.bottom_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(230)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.btn_add_new_lessons.sizePolicy().hasHeightForWidth())
        self.btn_add_new_lessons.setSizePolicy(sizePolicy)
        self.btn_add_new_lessons.setMinimumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_add_new_lessons.setFont(font)
        self.btn_add_new_lessons.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_add_new_lessons.setStyleSheet("QPushButton {\n"
"background-color: rgb(160, 253, 230);\n"
"color:  #256D85 ;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    \n"
"    background-color: rgb(143, 227, 207);\n"
"    color: #2B4865;\n"
"\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/add_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_new_lessons.setIcon(icon3)
        self.btn_add_new_lessons.setObjectName("btn_add_new_lessons")
        self.horizontalLayout_3.addWidget(self.btn_add_new_lessons)
        spacerItem4 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.btn_update_lessons = QtWidgets.QPushButton(self.bottom_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(230)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.btn_update_lessons.sizePolicy().hasHeightForWidth())
        self.btn_update_lessons.setSizePolicy(sizePolicy)
        self.btn_update_lessons.setMinimumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_update_lessons.setFont(font)
        self.btn_update_lessons.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_update_lessons.setStyleSheet("QPushButton {\n"
"background-color: rgb(160, 253, 230);\n"
"color:  #256D85 ;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    \n"
"    background-color: rgb(143, 227, 207);\n"
"    color: #2B4865;\n"
"\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/edit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_update_lessons.setIcon(icon4)
        self.btn_update_lessons.setObjectName("btn_update_lessons")
        self.horizontalLayout_3.addWidget(self.btn_update_lessons)
        spacerItem5 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.bottom_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_headline.setText(_translate("MainWindow", "পাঠসূচি"))
        self.lbl_category.setText(_translate("MainWindow", "ক্যাটাগরি"))
        self.cmb_category.setCurrentText(_translate("MainWindow", "ক্যাটাগরি নির্বাচন করুন"))
        self.cmb_category.setItemText(0, _translate("MainWindow", "ক্যাটাগরি নির্বাচন করুন"))
        self.cmb_category.setItemText(1, _translate("MainWindow", "নাম শিখন (Noun)"))
        self.cmb_category.setItemText(2, _translate("MainWindow", "ক্রিয়া শিখন (Verb)"))
        self.cmb_category.setItemText(3, _translate("MainWindow", "সম্পর্ক শিখন (Association)"))
        self.cmb_category.setItemText(4, _translate("MainWindow", "কর্মধারা শিখন (Activity)"))
        self.lbl_lessons.setText(_translate("MainWindow", "পাঠসমূহ"))
        self.cmb_lessons.setItemText(0, _translate("MainWindow", "পাঠ ক্রম নির্বাচন করুন"))
        self.lbl_image.setText(_translate("MainWindow", "ছবি"))
        self.lbl_image_text.setText(_translate("MainWindow", "পরিচয়"))
        self.btn_add_new_lessons.setText(_translate("MainWindow", "নতুন পাঠ যুক্ত করুন"))
        self.btn_update_lessons.setText(_translate("MainWindow", "পাঠ আপডেট করুন"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
