# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frontend/PyQT_UI/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.stackedWidget.setStyleSheet("background-color: #F4F1DE;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setMinimumSize(QtCore.QSize(1280, 600))
        self.home_page.setObjectName("home_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top_frame_3 = QtWidgets.QFrame(self.home_page)
        self.top_frame_3.setMinimumSize(QtCore.QSize(1300, 440))
        self.top_frame_3.setStyleSheet("")
        self.top_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_3.setObjectName("top_frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_frame_3)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_lesson = QtWidgets.QPushButton(self.top_frame_3)
        self.btn_lesson.setMaximumSize(QtCore.QSize(350, 280))
        self.btn_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_lesson.setStyleSheet("QPushButton {\n"
"border: 5px solid #E07A5F;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color: #3D405B;\n"
"color: #F4F1DE;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #F4F1DE;\n"
"color: #E07A5F;\n"
"}")
        self.btn_lesson.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Frontend/PyQT_UI\\../Images/lessons_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_lesson.setIcon(icon)
        self.btn_lesson.setIconSize(QtCore.QSize(400, 400))
        self.btn_lesson.setObjectName("btn_lesson")
        self.horizontalLayout.addWidget(self.btn_lesson)
        self.verticalLayout_3.addWidget(self.top_frame_3)
        self.bottom_frame_3 = QtWidgets.QFrame(self.home_page)
        self.bottom_frame_3.setMinimumSize(QtCore.QSize(1301, 151))
        self.bottom_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame_3.setObjectName("bottom_frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottom_frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.bottom_frame_3)
        self.label.setMinimumSize(QtCore.QSize(1280, 120))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Frontend/PyQT_UI\\../Images/banner_icon.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.bottom_frame_3)
        self.stackedWidget.addWidget(self.home_page)
        self.lesson_page = QtWidgets.QWidget()
        self.lesson_page.setMinimumSize(QtCore.QSize(1280, 720))
        self.lesson_page.setObjectName("lesson_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.lesson_page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame_2 = QtWidgets.QFrame(self.lesson_page)
        self.top_frame_2.setMinimumSize(QtCore.QSize(1280, 70))
        self.top_frame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.top_frame_2.setStyleSheet("background-color: #E07A5F;\n"
"color: #3D405B; ")
        self.top_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_2.setObjectName("top_frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.top_frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_back_to_home_2 = QtWidgets.QPushButton(self.top_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back_to_home_2.sizePolicy().hasHeightForWidth())
        self.btn_back_to_home_2.setSizePolicy(sizePolicy)
        self.btn_back_to_home_2.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_back_to_home_2.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_back_to_home_2.setBaseSize(QtCore.QSize(0, 4))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_back_to_home_2.setFont(font)
        self.btn_back_to_home_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_back_to_home_2.setMouseTracking(True)
        self.btn_back_to_home_2.setStyleSheet("QPushButton {\n"
"    background-color: ;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #F4F1DE;\n"
"    border-radius: 30px;\n"
"}")
        self.btn_back_to_home_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Frontend/PyQT_UI\\../Images/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back_to_home_2.setIcon(icon1)
        self.btn_back_to_home_2.setIconSize(QtCore.QSize(250, 250))
        self.btn_back_to_home_2.setAutoDefault(False)
        self.btn_back_to_home_2.setDefault(False)
        self.btn_back_to_home_2.setFlat(False)
        self.btn_back_to_home_2.setObjectName("btn_back_to_home_2")
        self.horizontalLayout_4.addWidget(self.btn_back_to_home_2)
        self.lbl_lesson_headline = QtWidgets.QLabel(self.top_frame_2)
        font = QtGui.QFont()
        font.setFamily("Kalpurush")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_lesson_headline.setFont(font)
        self.lbl_lesson_headline.setStyleSheet("color: rgb(0, 0, 0);\n"
"padding-left: 5px;\n"
"font: 30pt \"Kalpurush\";")
        self.lbl_lesson_headline.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lesson_headline.setObjectName("lbl_lesson_headline")
        self.horizontalLayout_4.addWidget(self.lbl_lesson_headline)
        self.verticalLayout.addWidget(self.top_frame_2)
        self.bottom_frame_2 = QtWidgets.QFrame(self.lesson_page)
        self.bottom_frame_2.setMinimumSize(QtCore.QSize(0, 550))
        self.bottom_frame_2.setStyleSheet("background-color: rgb(244, 241, 222);\n"
"border: none;")
        self.bottom_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame_2.setObjectName("bottom_frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.bottom_frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_prev_lesson = QtWidgets.QPushButton(self.bottom_frame_2)
        self.btn_prev_lesson.setMinimumSize(QtCore.QSize(70, 650))
        self.btn_prev_lesson.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_prev_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_prev_lesson.setStyleSheet("QPushButton {\n"
"border: 3px solid #E07A5F;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color: #3D405B;\n"
"color: #F4F1DE;\n"
"}")
        self.btn_prev_lesson.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Frontend/PyQT_UI\\../Images/backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev_lesson.setIcon(icon2)
        self.btn_prev_lesson.setIconSize(QtCore.QSize(150, 150))
        self.btn_prev_lesson.setObjectName("btn_prev_lesson")
        self.horizontalLayout_7.addWidget(self.btn_prev_lesson)
        self.lbl_image = QtWidgets.QLabel(self.bottom_frame_2)
        self.lbl_image.setEnabled(True)
        self.lbl_image.setMinimumSize(QtCore.QSize(800, 550))
        self.lbl_image.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lbl_image.setFont(font)
        self.lbl_image.setStyleSheet("border: 3px dashed rgb(222, 219, 202);\n"
"color:  rgb(61, 64, 91);")
        self.lbl_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image.setObjectName("lbl_image")
        self.horizontalLayout_7.addWidget(self.lbl_image)
        self.lbl_image_text = QtWidgets.QLabel(self.bottom_frame_2)
        self.lbl_image_text.setMinimumSize(QtCore.QSize(300, 500))
        self.lbl_image_text.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lbl_image_text.setFont(font)
        self.lbl_image_text.setStyleSheet("border: 3px dashed rgb(222, 219, 202);\n"
"color:  rgb(61, 64, 91);")
        self.lbl_image_text.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image_text.setWordWrap(True)
        self.lbl_image_text.setObjectName("lbl_image_text")
        self.horizontalLayout_7.addWidget(self.lbl_image_text)
        self.btn_next_lesson = QtWidgets.QPushButton(self.bottom_frame_2)
        self.btn_next_lesson.setMinimumSize(QtCore.QSize(70, 650))
        self.btn_next_lesson.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_next_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_next_lesson.setStyleSheet("QPushButton {\n"
"border: 3px solid #E07A5F;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color: #3D405B;\n"
"color: #F4F1DE;\n"
"}")
        self.btn_next_lesson.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Frontend/PyQT_UI\\../Images/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next_lesson.setIcon(icon3)
        self.btn_next_lesson.setIconSize(QtCore.QSize(100, 100))
        self.btn_next_lesson.setObjectName("btn_next_lesson")
        self.horizontalLayout_7.addWidget(self.btn_next_lesson)
        self.verticalLayout.addWidget(self.bottom_frame_2)
        self.stackedWidget.addWidget(self.lesson_page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_lesson_headline.setText(_translate("MainWindow", "নাম শিখন - পাঠ ১"))
        self.lbl_image.setText(_translate("MainWindow", "ছবি"))
        self.lbl_image_text.setText(_translate("MainWindow", "পরিচয়"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
