# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Frontend\PyQT_UI\home_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 700))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1280, 700))
        self.stackedWidget.setStyleSheet("background-color: #F4F1DE;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setMinimumSize(QtCore.QSize(1280, 600))
        self.home_page.setObjectName("home_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top_frame_3 = QtWidgets.QFrame(self.home_page)
        self.top_frame_3.setMinimumSize(QtCore.QSize(1300, 344))
        self.top_frame_3.setStyleSheet("")
        self.top_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_3.setObjectName("top_frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_frame_3)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_lesson = QtWidgets.QPushButton(self.top_frame_3)
        self.btn_lesson.setMaximumSize(QtCore.QSize(350, 280))
        self.btn_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_lesson.setStyleSheet("QPushButton {\n"
"border: 5px solid #E07A5F;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color: #3D405B;\n"
"color: #F4F1DE;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #F4F1DE;\n"
"color: #E07A5F;\n"
"}")
        self.btn_lesson.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQT_UI\\../Images/lessons_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_lesson.setIcon(icon)
        self.btn_lesson.setIconSize(QtCore.QSize(400, 400))
        self.btn_lesson.setObjectName("btn_lesson")
        self.horizontalLayout.addWidget(self.btn_lesson)
        self.verticalLayout_3.addWidget(self.top_frame_3)
        self.bottom_frame_3 = QtWidgets.QFrame(self.home_page)
        self.bottom_frame_3.setMinimumSize(QtCore.QSize(1301, 151))
        self.bottom_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame_3.setObjectName("bottom_frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottom_frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.bottom_frame_3)
        self.label.setMinimumSize(QtCore.QSize(1280, 120))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\Frontend\\PyQT_UI\\../Images/banner_icon.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.bottom_frame_3)
        self.stackedWidget.addWidget(self.home_page)
        self.lesson_page = QtWidgets.QWidget()
        self.lesson_page.setMinimumSize(QtCore.QSize(1280, 700))
        self.lesson_page.setObjectName("lesson_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.lesson_page)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.top_frame_2 = QtWidgets.QFrame(self.lesson_page)
        self.top_frame_2.setMinimumSize(QtCore.QSize(1280, 84))
        self.top_frame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.top_frame_2.setStyleSheet("background-color: #E07A5F;\n"
"color: #3D405B; ")
        self.top_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_2.setObjectName("top_frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.top_frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_back_to_home = QtWidgets.QPushButton(self.top_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back_to_home.sizePolicy().hasHeightForWidth())
        self.btn_back_to_home.setSizePolicy(sizePolicy)
        self.btn_back_to_home.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_back_to_home.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_back_to_home.setBaseSize(QtCore.QSize(0, 4))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_back_to_home.setFont(font)
        self.btn_back_to_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_back_to_home.setMouseTracking(True)
        self.btn_back_to_home.setStyleSheet("QPushButton {\n"
"    background-color: ;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #F4F1DE;\n"
"    border-radius: 30px;\n"
"}")
        self.btn_back_to_home.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQT_UI\\../Images/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back_to_home.setIcon(icon1)
        self.btn_back_to_home.setIconSize(QtCore.QSize(250, 250))
        self.btn_back_to_home.setAutoDefault(False)
        self.btn_back_to_home.setDefault(False)
        self.btn_back_to_home.setFlat(False)
        self.btn_back_to_home.setObjectName("btn_back_to_home")
        self.horizontalLayout_4.addWidget(self.btn_back_to_home)
        self.lbl_lesson_headline = QtWidgets.QLabel(self.top_frame_2)
        self.lbl_lesson_headline.setMinimumSize(QtCore.QSize(0, 67))
        font = QtGui.QFont()
        font.setFamily("Kalpurush")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_lesson_headline.setFont(font)
        self.lbl_lesson_headline.setStyleSheet("color: rgb(0, 0, 0);\n"
"padding-left: 5px;\n"
"font: 30pt \"Kalpurush\";")
        self.lbl_lesson_headline.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lesson_headline.setObjectName("lbl_lesson_headline")
        self.horizontalLayout_4.addWidget(self.lbl_lesson_headline)
        self.gridLayout_3.addWidget(self.top_frame_2, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.lesson_page)
        self.frame.setMinimumSize(QtCore.QSize(1280, 550))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(11, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_prev_lesson = QtWidgets.QPushButton(self.frame)
        self.btn_prev_lesson.setMinimumSize(QtCore.QSize(70, 600))
        self.btn_prev_lesson.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_prev_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_prev_lesson.setStyleSheet("QPushButton {\n"
"border: 3px solid #E07A5F;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color: #3D405B;\n"
"color: #F4F1DE;\n"
"}")
        self.btn_prev_lesson.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQT_UI\\../Images/backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev_lesson.setIcon(icon2)
        self.btn_prev_lesson.setIconSize(QtCore.QSize(150, 150))
        self.btn_prev_lesson.setObjectName("btn_prev_lesson")
        self.gridLayout.addWidget(self.btn_prev_lesson, 0, 0, 1, 1)
        self.middle_content_frame = QtWidgets.QFrame(self.frame)
        self.middle_content_frame.setMinimumSize(QtCore.QSize(1100, 611))
        self.middle_content_frame.setStyleSheet("background-color: rgb(244, 241, 222);\n"
"color: rgb(61, 64, 91);\n"
"border: none;")
        self.middle_content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.middle_content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middle_content_frame.setObjectName("middle_content_frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.middle_content_frame)
        self.horizontalLayout_12.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.mediaStackWidget = QtWidgets.QStackedWidget(self.middle_content_frame)
        self.mediaStackWidget.setMinimumSize(QtCore.QSize(690, 400))
        self.mediaStackWidget.setObjectName("mediaStackWidget")
        self.image_page = QtWidgets.QWidget()
        self.image_page.setObjectName("image_page")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.image_page)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lsn_lbl_image = QtWidgets.QLabel(self.image_page)
        self.lsn_lbl_image.setMinimumSize(QtCore.QSize(690, 380))
        font = QtGui.QFont()
        font.setFamily("Kalpurush")
        font.setPointSize(30)
        self.lsn_lbl_image.setFont(font)
        self.lsn_lbl_image.setStyleSheet("border: 3px dotted rgb(227, 224, 207) ;\n"
"color: rgb(61, 64, 91);")
        self.lsn_lbl_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lsn_lbl_image.setObjectName("lsn_lbl_image")
        self.horizontalLayout_9.addWidget(self.lsn_lbl_image)
        self.mediaStackWidget.addWidget(self.image_page)
        self.video_page = QtWidgets.QWidget()
        self.video_page.setObjectName("video_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.video_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.video_player_widget = QtWidgets.QHBoxLayout()
        self.video_player_widget.setObjectName("video_player_widget")
        self.verticalLayout_5.addLayout(self.video_player_widget)
        self.mediaStackWidget.addWidget(self.video_page)
        self.horizontalLayout_12.addWidget(self.mediaStackWidget)
        self.lsn_lbl_lesson_topic = QtWidgets.QLabel(self.middle_content_frame)
        self.lsn_lbl_lesson_topic.setMinimumSize(QtCore.QSize(380, 400))
        self.lsn_lbl_lesson_topic.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Kalpurush")
        font.setPointSize(25)
        self.lsn_lbl_lesson_topic.setFont(font)
        self.lsn_lbl_lesson_topic.setStyleSheet("border: 3px dotted rgb(227, 224, 207) ;\n"
"color: rgb(61, 64, 91);")
        self.lsn_lbl_lesson_topic.setAlignment(QtCore.Qt.AlignCenter)
        self.lsn_lbl_lesson_topic.setWordWrap(True)
        self.lsn_lbl_lesson_topic.setObjectName("lsn_lbl_lesson_topic")
        self.horizontalLayout_12.addWidget(self.lsn_lbl_lesson_topic)
        self.gridLayout.addWidget(self.middle_content_frame, 0, 1, 1, 1)
        self.btn_next_lesson = QtWidgets.QPushButton(self.frame)
        self.btn_next_lesson.setMinimumSize(QtCore.QSize(70, 600))
        self.btn_next_lesson.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_next_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_next_lesson.setStyleSheet("QPushButton {\n"
"border: 3px solid #E07A5F;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color: #3D405B;\n"
"color: #F4F1DE;\n"
"}")
        self.btn_next_lesson.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQT_UI\\../Images/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next_lesson.setIcon(icon3)
        self.btn_next_lesson.setIconSize(QtCore.QSize(150, 150))
        self.btn_next_lesson.setObjectName("btn_next_lesson")
        self.gridLayout.addWidget(self.btn_next_lesson, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.lesson_page)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.mediaStackWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_lesson_headline.setText(_translate("MainWindow", "নাম শিখন - পাঠ ১"))
        self.lsn_lbl_image.setText(_translate("MainWindow", "ছবি"))
        self.lsn_lbl_lesson_topic.setText(_translate("MainWindow", "পরিচয়"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
