# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Frontend\PyQT_UI\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1322, 923)
        MainWindow.setMinimumSize(QtCore.QSize(1322, 923))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1300, 900))
        self.stackedWidget.setStyleSheet("background-color: #F4F1DE;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.upload_lesson_page = QtWidgets.QWidget()
        self.upload_lesson_page.setObjectName("upload_lesson_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.upload_lesson_page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.top_frame = QtWidgets.QFrame(self.upload_lesson_page)
        self.top_frame.setMinimumSize(QtCore.QSize(1280, 95))
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.top_frame.setStyleSheet("background-color: #E07A5F;\n"
"color: #3D405B; ")
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_back_to_home = QtWidgets.QPushButton(self.top_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back_to_home.sizePolicy().hasHeightForWidth())
        self.btn_back_to_home.setSizePolicy(sizePolicy)
        self.btn_back_to_home.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_back_to_home.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_back_to_home.setBaseSize(QtCore.QSize(0, 4))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_back_to_home.setFont(font)
        self.btn_back_to_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_back_to_home.setMouseTracking(True)
        self.btn_back_to_home.setStyleSheet("QPushButton {\n"
"    background-color: ;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #F4F1DE;\n"
"    border-radius: 30px;\n"
"}")
        self.btn_back_to_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQT_UI\\../Images/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back_to_home.setIcon(icon)
        self.btn_back_to_home.setIconSize(QtCore.QSize(200, 200))
        self.btn_back_to_home.setAutoDefault(False)
        self.btn_back_to_home.setDefault(False)
        self.btn_back_to_home.setFlat(False)
        self.btn_back_to_home.setObjectName("btn_back_to_home")
        self.horizontalLayout_3.addWidget(self.btn_back_to_home)
        self.lbl_headline = QtWidgets.QLabel(self.top_frame)
        font = QtGui.QFont()
        font.setFamily("Kalpurush")
        font.setPointSize(30)
        self.lbl_headline.setFont(font)
        self.lbl_headline.setStyleSheet("color: rgb(0, 0, 0);\n"
"padding-left: 5px;")
        self.lbl_headline.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_headline.setObjectName("lbl_headline")
        self.horizontalLayout_3.addWidget(self.lbl_headline)
        self.gridLayout_2.addWidget(self.top_frame, 0, 0, 1, 1)
        self.bottom_frame = QtWidgets.QFrame(self.upload_lesson_page)
        self.bottom_frame.setMinimumSize(QtCore.QSize(1280, 700))
        self.bottom_frame.setStyleSheet("border: 2px solid rgb(224, 122, 95);")
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.bottom_frame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(407, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 2)
        self.btn_select_folder = QtWidgets.QPushButton(self.bottom_frame)
        self.btn_select_folder.setMinimumSize(QtCore.QSize(450, 80))
        self.btn_select_folder.setMaximumSize(QtCore.QSize(350, 350))
        font = QtGui.QFont()
        font.setFamily("Kalpurush")
        font.setPointSize(20)
        self.btn_select_folder.setFont(font)
        self.btn_select_folder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_select_folder.setMouseTracking(False)
        self.btn_select_folder.setStyleSheet("QPushButton {\n"
"border: 5px solid #E07A5F;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color: #3D405B;\n"
"color: #F4F1DE;\n"
"}")
        self.btn_select_folder.setIconSize(QtCore.QSize(400, 400))
        self.btn_select_folder.setObjectName("btn_select_folder")
        self.gridLayout.addWidget(self.btn_select_folder, 1, 2, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(378, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 5, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(297, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 1)
        self.edit_lesson_list = QtWidgets.QTextEdit(self.bottom_frame)
        self.edit_lesson_list.setMinimumSize(QtCore.QSize(650, 220))
        font = QtGui.QFont()
        font.setFamily("Kalpurush")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edit_lesson_list.setFont(font)
        self.edit_lesson_list.setStyleSheet("border: 2px solid rgb(224, 122, 95);\n"
"padding-left: 10px;")
        self.edit_lesson_list.setObjectName("edit_lesson_list")
        self.gridLayout.addWidget(self.edit_lesson_list, 3, 1, 1, 5)
        spacerItem5 = QtWidgets.QSpacerItem(297, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 3, 6, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 4, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(507, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 5, 0, 1, 3)
        self.bnt_start_lesson = QtWidgets.QPushButton(self.bottom_frame)
        self.bnt_start_lesson.setEnabled(False)
        self.bnt_start_lesson.setMinimumSize(QtCore.QSize(250, 60))
        self.bnt_start_lesson.setMaximumSize(QtCore.QSize(250, 350))
        font = QtGui.QFont()
        font.setFamily("Kalpurush")
        font.setPointSize(20)
        self.bnt_start_lesson.setFont(font)
        self.bnt_start_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bnt_start_lesson.setMouseTracking(False)
        self.bnt_start_lesson.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(61, 64, 91);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color: rgb(224, 122, 95);\n"
"color: #F4F1DE;\n"
"}")
        self.bnt_start_lesson.setIconSize(QtCore.QSize(400, 400))
        self.bnt_start_lesson.setObjectName("bnt_start_lesson")
        self.gridLayout.addWidget(self.bnt_start_lesson, 5, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(497, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 5, 4, 1, 3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem9, 6, 3, 1, 1)
        self.gridLayout_2.addWidget(self.bottom_frame, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.upload_lesson_page)
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top_frame_3 = QtWidgets.QFrame(self.home_page)
        self.top_frame_3.setMinimumSize(QtCore.QSize(1300, 650))
        self.top_frame_3.setStyleSheet("")
        self.top_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_3.setObjectName("top_frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_frame_3)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_lesson = QtWidgets.QPushButton(self.top_frame_3)
        self.btn_lesson.setMaximumSize(QtCore.QSize(350, 350))
        self.btn_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_lesson.setStyleSheet("QPushButton {\n"
"border: 5px solid #E07A5F;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color: #3D405B;\n"
"color: #F4F1DE;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #F4F1DE;\n"
"color: #E07A5F;\n"
"}")
        self.btn_lesson.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQT_UI\\../Images/lessons_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_lesson.setIcon(icon1)
        self.btn_lesson.setIconSize(QtCore.QSize(400, 400))
        self.btn_lesson.setObjectName("btn_lesson")
        self.horizontalLayout.addWidget(self.btn_lesson)
        self.btn_evaluation = QtWidgets.QPushButton(self.top_frame_3)
        self.btn_evaluation.setMaximumSize(QtCore.QSize(350, 350))
        self.btn_evaluation.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_evaluation.setMouseTracking(False)
        self.btn_evaluation.setStyleSheet("QPushButton {\n"
"border: 5px solid #E07A5F;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color: #3D405B;\n"
"color: #F4F1DE;\n"
"}")
        self.btn_evaluation.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQT_UI\\../Images/evaluation_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_evaluation.setIcon(icon2)
        self.btn_evaluation.setIconSize(QtCore.QSize(400, 400))
        self.btn_evaluation.setObjectName("btn_evaluation")
        self.horizontalLayout.addWidget(self.btn_evaluation)
        self.verticalLayout_3.addWidget(self.top_frame_3)
        self.bottom_frame_3 = QtWidgets.QFrame(self.home_page)
        self.bottom_frame_3.setMinimumSize(QtCore.QSize(1301, 151))
        self.bottom_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame_3.setObjectName("bottom_frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottom_frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.bottom_frame_3)
        self.label.setMinimumSize(QtCore.QSize(1300, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\Frontend\\PyQT_UI\\../Images/banner_icon.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.bottom_frame_3)
        self.stackedWidget.addWidget(self.home_page)
        self.lesson_page = QtWidgets.QWidget()
        self.lesson_page.setObjectName("lesson_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.lesson_page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame_2 = QtWidgets.QFrame(self.lesson_page)
        self.top_frame_2.setMinimumSize(QtCore.QSize(1280, 95))
        self.top_frame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.top_frame_2.setStyleSheet("background-color: #E07A5F;\n"
"color: #3D405B; ")
        self.top_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_2.setObjectName("top_frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.top_frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_back_to_home_2 = QtWidgets.QPushButton(self.top_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back_to_home_2.sizePolicy().hasHeightForWidth())
        self.btn_back_to_home_2.setSizePolicy(sizePolicy)
        self.btn_back_to_home_2.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_back_to_home_2.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_back_to_home_2.setBaseSize(QtCore.QSize(0, 4))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_back_to_home_2.setFont(font)
        self.btn_back_to_home_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_back_to_home_2.setMouseTracking(True)
        self.btn_back_to_home_2.setStyleSheet("QPushButton {\n"
"    background-color: ;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color: #F4F1DE;\n"
"    border-radius: 30px;\n"
"}")
        self.btn_back_to_home_2.setText("")
        self.btn_back_to_home_2.setIcon(icon)
        self.btn_back_to_home_2.setIconSize(QtCore.QSize(250, 250))
        self.btn_back_to_home_2.setAutoDefault(False)
        self.btn_back_to_home_2.setDefault(False)
        self.btn_back_to_home_2.setFlat(False)
        self.btn_back_to_home_2.setObjectName("btn_back_to_home_2")
        self.horizontalLayout_4.addWidget(self.btn_back_to_home_2)
        self.lbl_headline_2 = QtWidgets.QLabel(self.top_frame_2)
        font = QtGui.QFont()
        font.setFamily("Kalpurush")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_headline_2.setFont(font)
        self.lbl_headline_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"padding-left: 5px;\n"
"font: 30pt \"Kalpurush\";")
        self.lbl_headline_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_headline_2.setObjectName("lbl_headline_2")
        self.horizontalLayout_4.addWidget(self.lbl_headline_2)
        self.verticalLayout.addWidget(self.top_frame_2)
        self.bottom_frame_2 = QtWidgets.QFrame(self.lesson_page)
        self.bottom_frame_2.setStyleSheet("background-color: rgb(244, 241, 222);\n"
"border: none;")
        self.bottom_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame_2.setObjectName("bottom_frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.bottom_frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_prev_lesson = QtWidgets.QPushButton(self.bottom_frame_2)
        self.btn_prev_lesson.setMinimumSize(QtCore.QSize(70, 777))
        self.btn_prev_lesson.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_prev_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_prev_lesson.setStyleSheet("QPushButton {\n"
"border: 3px solid #E07A5F;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color: #3D405B;\n"
"color: #F4F1DE;\n"
"}")
        self.btn_prev_lesson.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQT_UI\\../Images/backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev_lesson.setIcon(icon3)
        self.btn_prev_lesson.setIconSize(QtCore.QSize(150, 150))
        self.btn_prev_lesson.setObjectName("btn_prev_lesson")
        self.horizontalLayout_7.addWidget(self.btn_prev_lesson)
        self.lbl_image = QtWidgets.QLabel(self.bottom_frame_2)
        self.lbl_image.setMinimumSize(QtCore.QSize(800, 777))
        self.lbl_image.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lbl_image.setFont(font)
        self.lbl_image.setStyleSheet("border: 3px dashed rgb(222, 219, 202);\n"
"color:  rgb(61, 64, 91);")
        self.lbl_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image.setObjectName("lbl_image")
        self.horizontalLayout_7.addWidget(self.lbl_image)
        self.lbl_image_text = QtWidgets.QLabel(self.bottom_frame_2)
        self.lbl_image_text.setMinimumSize(QtCore.QSize(300, 777))
        self.lbl_image_text.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lbl_image_text.setFont(font)
        self.lbl_image_text.setStyleSheet("border: 3px dashed rgb(222, 219, 202);\n"
"color:  rgb(61, 64, 91);")
        self.lbl_image_text.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image_text.setWordWrap(True)
        self.lbl_image_text.setObjectName("lbl_image_text")
        self.horizontalLayout_7.addWidget(self.lbl_image_text)
        self.btn_next_lesson = QtWidgets.QPushButton(self.bottom_frame_2)
        self.btn_next_lesson.setMinimumSize(QtCore.QSize(70, 777))
        self.btn_next_lesson.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_next_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_next_lesson.setStyleSheet("QPushButton {\n"
"border: 3px solid #E07A5F;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color: #3D405B;\n"
"color: #F4F1DE;\n"
"}")
        self.btn_next_lesson.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQT_UI\\../Images/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next_lesson.setIcon(icon4)
        self.btn_next_lesson.setIconSize(QtCore.QSize(100, 100))
        self.btn_next_lesson.setObjectName("btn_next_lesson")
        self.horizontalLayout_7.addWidget(self.btn_next_lesson)
        self.verticalLayout.addWidget(self.bottom_frame_2)
        self.stackedWidget.addWidget(self.lesson_page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_headline.setText(_translate("MainWindow", "পাঠসমূহ "))
        self.btn_select_folder.setText(_translate("MainWindow", "ফোল্ডার নির্বাচন করুন"))
        self.edit_lesson_list.setPlaceholderText(_translate("MainWindow", "পাঠসমূহ  "))
        self.bnt_start_lesson.setText(_translate("MainWindow", "শুরু করুন"))
        self.lbl_headline_2.setText(_translate("MainWindow", "নাম শিখন - পাঠ ১"))
        self.lbl_image.setText(_translate("MainWindow", "ছবি"))
        self.lbl_image_text.setText(_translate("MainWindow", "পরিচয়"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
