# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lesson.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.LessonPage = QtWidgets.QWidget(MainWindow)
        self.LessonPage.setObjectName("LessonPage")
        self.textEdit = QtWidgets.QTextEdit(self.LessonPage)
        self.textEdit.setGeometry(QtCore.QRect(280, 160, 104, 71))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.LessonPage)
        self.label.setGeometry(QtCore.QRect(210, 180, 51, 31))
        self.label.setObjectName("label")
        self.SubmitButton = QtWidgets.QPushButton(self.LessonPage)
        self.SubmitButton.setGeometry(QtCore.QRect(290, 250, 75, 23))
        self.SubmitButton.setObjectName("SubmitButton")
        self.CreateLesson = QtWidgets.QPushButton(self.LessonPage)
        self.CreateLesson.setGeometry(QtCore.QRect(220, 450, 181, 23))
        self.CreateLesson.setObjectName("CreateLesson")
        MainWindow.setCentralWidget(self.LessonPage)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Add Text"))
        self.SubmitButton.setText(_translate("MainWindow", "Submit"))
        self.CreateLesson.setText(_translate("MainWindow", "Create Lesson"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
