# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addNum.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.firstNum = QtWidgets.QLabel(Dialog)
        self.firstNum.setGeometry(QtCore.QRect(70, 40, 47, 13))
        self.firstNum.setObjectName("firstNum")
        self.secondNum = QtWidgets.QLabel(Dialog)
        self.secondNum.setGeometry(QtCore.QRect(60, 110, 61, 20))
        self.secondNum.setObjectName("secondNum")
        self.firstNumBox = QtWidgets.QLineEdit(Dialog)
        self.firstNumBox.setGeometry(QtCore.QRect(160, 40, 113, 20))
        self.firstNumBox.setObjectName("firstNumBox")
        self.secondNumBox = QtWidgets.QLineEdit(Dialog)
        self.secondNumBox.setGeometry(QtCore.QRect(160, 110, 113, 20))
        self.secondNumBox.setObjectName("secondNumBox")
        self.sum = QtWidgets.QLabel(Dialog)
        self.sum.setGeometry(QtCore.QRect(100, 200, 61, 20))
        self.sum.setObjectName("sum")
        self.sumBox = QtWidgets.QLineEdit(Dialog)
        self.sumBox.setGeometry(QtCore.QRect(150, 200, 113, 20))
        self.sumBox.setObjectName("sumBox")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(180, 150, 75, 23))
        self.addButton.setObjectName("addButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.firstNum.setText(_translate("Dialog", "First num"))
        self.secondNum.setText(_translate("Dialog", "Second num"))
        self.sum.setText(_translate("Dialog", "Sum"))
        self.addButton.setText(_translate("Dialog", "ADD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
