# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audioRecorder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.audio = QtWidgets.QWidget(self.centralwidget)
        self.audio.setGeometry(QtCore.QRect(79, 110, 621, 351))
        self.audio.setObjectName("audio")
        self.textLabel = QtWidgets.QLabel(self.audio)
        self.textLabel.setGeometry(QtCore.QRect(220, 30, 201, 41))
        self.textLabel.setStyleSheet("font-size: 15px;\n"
"text-align: center;")
        self.textLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel.setObjectName("textLabel")
        self.recordBtton = QtWidgets.QPushButton(self.audio)
        self.recordBtton.setGeometry(QtCore.QRect(200, 190, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.recordBtton.setFont(font)
        self.recordBtton.setStyleSheet("")
        self.recordBtton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("microphone_32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recordBtton.setIcon(icon)
        self.recordBtton.setIconSize(QtCore.QSize(70, 70))
        self.recordBtton.setObjectName("recordBtton")
        self.pushButton_2 = QtWidgets.QPushButton(self.audio)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 200, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pause_button_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textLabel.setText(_translate("MainWindow", "সাউন্ড রেকর্ড করুন "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
