# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Frontend\PyQT_UI\student_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Student_Info(object):
    def setupUi(self, Student_Info):
        Student_Info.setObjectName("Student_Info")
        Student_Info.resize(471, 603)
        self.verticalLayout = QtWidgets.QVBoxLayout(Student_Info)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame_7 = QtWidgets.QFrame(Student_Info)
        self.top_frame_7.setMinimumSize(QtCore.QSize(471, 100))
        self.top_frame_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.top_frame_7.setStyleSheet("background-color: #E07A5F;\n"
"color: #3D405B; ")
        self.top_frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_7.setObjectName("top_frame_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.top_frame_7)
        self.gridLayout_11.setContentsMargins(11, 11, 0, 4)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lbl_mcq_heading = QtWidgets.QLabel(self.top_frame_7)
        self.lbl_mcq_heading.setMinimumSize(QtCore.QSize(300, 58))
        font = QtGui.QFont()
        font.setFamily("Kalpurush")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_mcq_heading.setFont(font)
        self.lbl_mcq_heading.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 26pt \"Kalpurush\";")
        self.lbl_mcq_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mcq_heading.setObjectName("lbl_mcq_heading")
        self.gridLayout_11.addWidget(self.lbl_mcq_heading, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.top_frame_7)
        self.frame = QtWidgets.QFrame(Student_Info)
        self.frame.setMinimumSize(QtCore.QSize(451, 311))
        self.frame.setStyleSheet("background-color: rgb(243, 240, 221);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setVerticalSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setMinimumSize(QtCore.QSize(131, 51))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Kalpurush")
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(224, 122, 95);\n"
"color: #000;\n"
"border-radius: 10px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.lbl_std_name = QtWidgets.QLineEdit(self.frame)
        self.lbl_std_name.setMinimumSize(QtCore.QSize(300, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_std_name.setFont(font)
        self.lbl_std_name.setStyleSheet("border: 3px solid #E07A5F;\n"
"background-color:#3D405B;\n"
"border-radius: 10px;\n"
"color: rgb(255, 170, 127);\n"
"padding-left: 15px;")
        self.lbl_std_name.setObjectName("lbl_std_name")
        self.gridLayout.addWidget(self.lbl_std_name, 1, 1, 1, 1)
        self.lbl_std_image = QtWidgets.QLabel(self.frame)
        self.lbl_std_image.setStyleSheet("border: 3px dashed rgb(0, 43, 91);")
        self.lbl_std_image.setText("")
        self.lbl_std_image.setPixmap(QtGui.QPixmap(".\\Frontend\\PyQT_UI\\../Images/gallery2.png"))
        self.lbl_std_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_std_image.setObjectName("lbl_std_image")
        self.gridLayout.addWidget(self.lbl_std_image, 0, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setMinimumSize(QtCore.QSize(131, 51))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Kalpurush")
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(224, 122, 95);\n"
"color: #000;\n"
"border-radius: 10px;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.lbl_std_id = QtWidgets.QLineEdit(self.frame)
        self.lbl_std_id.setMinimumSize(QtCore.QSize(300, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_std_id.setFont(font)
        self.lbl_std_id.setStyleSheet("border: 3px solid #E07A5F;\n"
"background-color:#3D405B;\n"
"border-radius: 10px;\n"
"color: rgb(255, 170, 127);\n"
"padding-left: 15px;")
        self.lbl_std_id.setObjectName("lbl_std_id")
        self.gridLayout.addWidget(self.lbl_std_id, 2, 1, 1, 1)
        self.btn_submit = QtWidgets.QPushButton(self.frame)
        self.btn_submit.setMinimumSize(QtCore.QSize(309, 48))
        font = QtGui.QFont()
        font.setFamily("Kalpurush")
        font.setPointSize(12)
        self.btn_submit.setFont(font)
        self.btn_submit.setStyleSheet("QPushButton {\n"
"border: 3px solid #E07A5F;\n"
"background-color:#3D405B;\n"
"border-radius: 20px;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color: #E07A5F;\n"
"color: #fff;\n"
"border: 3px solid #3D405B;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"        background-color:#3D405B; /* Selected state color */\n"
"        color: white;\n"
"}")
        self.btn_submit.setObjectName("btn_submit")
        self.gridLayout.addWidget(self.btn_submit, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Student_Info)
        QtCore.QMetaObject.connectSlotsByName(Student_Info)

    def retranslateUi(self, Student_Info):
        _translate = QtCore.QCoreApplication.translate
        Student_Info.setWindowTitle(_translate("Student_Info", "Form"))
        self.lbl_mcq_heading.setText(_translate("Student_Info", "পরিচয়"))
        self.label_8.setText(_translate("Student_Info", "নাম"))
        self.label_10.setText(_translate("Student_Info", "আইডি"))
        self.btn_submit.setText(_translate("Student_Info", "সাবমিট করুন"))
        self.btn_submit.setShortcut(_translate("Student_Info", "Return"))


def run():
        
    app = QtWidgets.QApplication(sys.argv)
    Student_Info = QtWidgets.QWidget()
    ui = Ui_Student_Info()
    ui.setupUi(Student_Info)
    Student_Info.show()
    sys.exit(app.exec_())
