# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Frontend\PyQt_UI\assign_lesson_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(521, 481)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.top_frame = QtWidgets.QFrame(Form)
        self.top_frame.setMinimumSize(QtCore.QSize(521, 90))
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.top_frame.setStyleSheet("background-color: rgb(43, 72, 101);")
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_heading = QtWidgets.QLabel(self.top_frame)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_heading.setFont(font)
        self.lbl_heading.setStyleSheet("color: rgb(143, 227, 207);")
        self.lbl_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_heading.setObjectName("lbl_heading")
        self.horizontalLayout.addWidget(self.lbl_heading)
        self.gridLayout_2.addWidget(self.top_frame, 0, 0, 1, 1)
        self.middle_frame = QtWidgets.QFrame(Form)
        self.middle_frame.setMinimumSize(QtCore.QSize(521, 391))
        self.middle_frame.setStyleSheet("background-color: rgb(32, 94, 115);\n"
"color: rgb(137, 218, 199);")
        self.middle_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.middle_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middle_frame.setObjectName("middle_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.middle_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.middle_frame)
        self.frame_3.setMinimumSize(QtCore.QSize(300, 80))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(-1, -1, 15, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_category = QtWidgets.QLabel(self.frame_3)
        self.lbl_category.setMinimumSize(QtCore.QSize(120, 0))
        self.lbl_category.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_category.setFont(font)
        self.lbl_category.setStyleSheet("color: rgb(137, 218, 199);")
        self.lbl_category.setObjectName("lbl_category")
        self.horizontalLayout_5.addWidget(self.lbl_category)
        self.lsn_cmb_lesson_list = QtWidgets.QComboBox(self.frame_3)
        self.lsn_cmb_lesson_list.setMinimumSize(QtCore.QSize(308, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        self.lsn_cmb_lesson_list.setFont(font)
        self.lsn_cmb_lesson_list.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"padding-left: 15px;\n"
"border-radius: 10px;\n"
"color: rgb(43, 72, 101);")
        self.lsn_cmb_lesson_list.setObjectName("lsn_cmb_lesson_list")
        self.lsn_cmb_lesson_list.addItem("")
        self.horizontalLayout_5.addWidget(self.lsn_cmb_lesson_list)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.middle_frame)
        self.frame_6.setMinimumSize(QtCore.QSize(497, 72))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_lesson_id = QtWidgets.QLabel(self.frame_6)
        self.lbl_lesson_id.setMinimumSize(QtCore.QSize(151, 48))
        self.lbl_lesson_id.setMaximumSize(QtCore.QSize(211, 16777215))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_lesson_id.setFont(font)
        self.lbl_lesson_id.setStyleSheet("color: rgb(137, 218, 199);")
        self.lbl_lesson_id.setObjectName("lbl_lesson_id")
        self.horizontalLayout_2.addWidget(self.lbl_lesson_id)
        self.lsn_edit_student_id = QtWidgets.QLineEdit(self.frame_6)
        self.lsn_edit_student_id.setEnabled(False)
        self.lsn_edit_student_id.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lsn_edit_student_id.setFont(font)
        self.lsn_edit_student_id.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"border: 2px solid rgb(101, 161, 146);\n"
"padding-left: 15px;\n"
"border-radius: 10px;\n"
"color: rgb(43, 72, 101);")
        self.lsn_edit_student_id.setCursorPosition(0)
        self.lsn_edit_student_id.setPlaceholderText("")
        self.lsn_edit_student_id.setObjectName("lsn_edit_student_id")
        self.horizontalLayout_2.addWidget(self.lsn_edit_student_id)
        self.gridLayout.addWidget(self.frame_6, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.middle_frame)
        self.frame_2.setMinimumSize(QtCore.QSize(501, 74))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_lesson_topic = QtWidgets.QLabel(self.frame_2)
        self.lbl_lesson_topic.setMinimumSize(QtCore.QSize(151, 0))
        self.lbl_lesson_topic.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_lesson_topic.setFont(font)
        self.lbl_lesson_topic.setStyleSheet("color: rgb(137, 218, 199);")
        self.lbl_lesson_topic.setObjectName("lbl_lesson_topic")
        self.horizontalLayout_6.addWidget(self.lbl_lesson_topic)
        self.lsn_edit_student_name = QtWidgets.QLineEdit(self.frame_2)
        self.lsn_edit_student_name.setEnabled(False)
        self.lsn_edit_student_name.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(11)
        self.lsn_edit_student_name.setFont(font)
        self.lsn_edit_student_name.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"border: 2px solid rgb(101, 161, 146);\n"
"padding-left: 15px;\n"
"border-radius: 10px;\n"
"color: rgb(43, 72, 101);")
        self.lsn_edit_student_name.setPlaceholderText("")
        self.lsn_edit_student_name.setObjectName("lsn_edit_student_name")
        self.horizontalLayout_6.addWidget(self.lsn_edit_student_name)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1)
        self.lsn_btn_assign_lsn_to_std = QtWidgets.QPushButton(self.middle_frame)
        self.lsn_btn_assign_lsn_to_std.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        self.lsn_btn_assign_lsn_to_std.setFont(font)
        self.lsn_btn_assign_lsn_to_std.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lsn_btn_assign_lsn_to_std.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(43, 72, 101);\n"
"border-radius: 10px;\n"
"background-color:  #002B5B;\n"
"color: rgb(137, 218, 199)\n"
"}\n"
"\n"
"QPushButton::hover:!pressed {\n"
"background-color: rgb(43, 72, 101);\n"
"border: 3px solid rgb(0, 43, 91); \n"
"}")
        self.lsn_btn_assign_lsn_to_std.setFlat(True)
        self.lsn_btn_assign_lsn_to_std.setObjectName("lsn_btn_assign_lsn_to_std")
        self.gridLayout.addWidget(self.lsn_btn_assign_lsn_to_std, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 52, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.middle_frame, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_heading.setText(_translate("Form", "পাঠ বরাদ্দকরণ উইন্ডো"))
        self.lbl_category.setText(_translate("Form", "পাঠসমূহ"))
        self.lsn_cmb_lesson_list.setItemText(0, _translate("Form", "পাঠ নির্বাচন করুন"))
        self.lbl_lesson_id.setText(_translate("Form", "শিক্ষার্থীর আইডি"))
        self.lbl_lesson_topic.setText(_translate("Form", "শিক্ষার্থীর নাম"))
        self.lsn_btn_assign_lsn_to_std.setText(_translate("Form", "পাঠ বরাদ্দ করুন"))
        self.lsn_btn_assign_lsn_to_std.setShortcut(_translate("Form", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
