# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Frontend\PyQt_UI\add_lesson_content.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(656, 809)
        Form.setMinimumSize(QtCore.QSize(656, 809))
        Form.setMaximumSize(QtCore.QSize(670, 809))
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.top_frame = QtWidgets.QFrame(Form)
        self.top_frame.setMinimumSize(QtCore.QSize(641, 90))
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 90))
        self.top_frame.setStyleSheet("background-color: rgb(43, 72, 101);")
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_heading = QtWidgets.QLabel(self.top_frame)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_heading.setFont(font)
        self.lbl_heading.setStyleSheet("color: rgb(143, 227, 207);")
        self.lbl_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_heading.setObjectName("lbl_heading")
        self.horizontalLayout.addWidget(self.lbl_heading)
        self.gridLayout_2.addWidget(self.top_frame, 0, 0, 1, 1)
        self.middle_frame = QtWidgets.QFrame(Form)
        self.middle_frame.setMinimumSize(QtCore.QSize(641, 710))
        self.middle_frame.setStyleSheet("background-color: rgb(32, 94, 115);\n"
"color: rgb(137, 218, 199);")
        self.middle_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.middle_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middle_frame.setObjectName("middle_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.middle_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.middle_frame)
        self.frame_3.setMinimumSize(QtCore.QSize(630, 80))
        self.frame_3.setMaximumSize(QtCore.QSize(493, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(-1, -1, 15, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_category = QtWidgets.QLabel(self.frame_3)
        self.lbl_category.setMinimumSize(QtCore.QSize(120, 0))
        self.lbl_category.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_category.setFont(font)
        self.lbl_category.setStyleSheet("color: rgb(137, 218, 199);")
        self.lbl_category.setObjectName("lbl_category")
        self.horizontalLayout_5.addWidget(self.lbl_category)
        self.cmb_category = QtWidgets.QComboBox(self.frame_3)
        self.cmb_category.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        self.cmb_category.setFont(font)
        self.cmb_category.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"padding-left: 15px;\n"
"border-radius: 10px;\n"
"color: rgb(43, 72, 101);")
        self.cmb_category.setObjectName("cmb_category")
        self.cmb_category.addItem("")
        self.cmb_category.addItem("")
        self.cmb_category.addItem("")
        self.cmb_category.addItem("")
        self.cmb_category.addItem("")
        self.horizontalLayout_5.addWidget(self.cmb_category)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 3)
        self.frame_6 = QtWidgets.QFrame(self.middle_frame)
        self.frame_6.setMinimumSize(QtCore.QSize(630, 71))
        self.frame_6.setMaximumSize(QtCore.QSize(600, 72))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_lesson_id = QtWidgets.QLabel(self.frame_6)
        self.lbl_lesson_id.setMinimumSize(QtCore.QSize(151, 0))
        self.lbl_lesson_id.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_lesson_id.setFont(font)
        self.lbl_lesson_id.setStyleSheet("color: rgb(137, 218, 199);")
        self.lbl_lesson_id.setObjectName("lbl_lesson_id")
        self.horizontalLayout_3.addWidget(self.lbl_lesson_id)
        self.edit_lesson_id = QtWidgets.QLineEdit(self.frame_6)
        self.edit_lesson_id.setMinimumSize(QtCore.QSize(325, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.edit_lesson_id.setFont(font)
        self.edit_lesson_id.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"border: 2px solid rgb(101, 161, 146);\n"
"padding-left: 15px;\n"
"border-radius: 10px;\n"
"color: rgb(43, 72, 101);")
        self.edit_lesson_id.setCursorPosition(0)
        self.edit_lesson_id.setObjectName("edit_lesson_id")
        self.horizontalLayout_3.addWidget(self.edit_lesson_id)
        self.gridLayout_3.addWidget(self.frame_6, 1, 0, 1, 3)
        self.frame_2 = QtWidgets.QFrame(self.middle_frame)
        self.frame_2.setMinimumSize(QtCore.QSize(630, 71))
        self.frame_2.setMaximumSize(QtCore.QSize(600, 72))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_lesson_topic = QtWidgets.QLabel(self.frame_2)
        self.lbl_lesson_topic.setMinimumSize(QtCore.QSize(151, 0))
        self.lbl_lesson_topic.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_lesson_topic.setFont(font)
        self.lbl_lesson_topic.setStyleSheet("color: rgb(137, 218, 199);")
        self.lbl_lesson_topic.setObjectName("lbl_lesson_topic")
        self.horizontalLayout_6.addWidget(self.lbl_lesson_topic)
        self.edit_lesson_topic = QtWidgets.QLineEdit(self.frame_2)
        self.edit_lesson_topic.setMinimumSize(QtCore.QSize(448, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(11)
        self.edit_lesson_topic.setFont(font)
        self.edit_lesson_topic.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"border: 2px solid rgb(101, 161, 146);\n"
"padding-left: 15px;\n"
"border-radius: 10px;\n"
"color: rgb(43, 72, 101);")
        self.edit_lesson_topic.setObjectName("edit_lesson_topic")
        self.horizontalLayout_6.addWidget(self.edit_lesson_topic)
        self.gridLayout_3.addWidget(self.frame_2, 2, 0, 1, 3)
        self.frame = QtWidgets.QFrame(self.middle_frame)
        self.frame.setMinimumSize(QtCore.QSize(630, 71))
        self.frame.setMaximumSize(QtCore.QSize(491, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_select_photo = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select_photo.sizePolicy().hasHeightForWidth())
        self.btn_select_photo.setSizePolicy(sizePolicy)
        self.btn_select_photo.setMinimumSize(QtCore.QSize(200, 50))
        self.btn_select_photo.setMaximumSize(QtCore.QSize(150, 51))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(11)
        self.btn_select_photo.setFont(font)
        self.btn_select_photo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_select_photo.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(43, 72, 101);\n"
"border-radius: 10px;\n"
"background-color:  rgb(43, 72, 101);\n"
"color: rgb(137, 218, 199)\n"
"}\n"
"\n"
"QPushButton::hover:!pressed {\n"
"background-color: rgb(0, 43, 91);\n"
"border: 3px solid rgb(0, 43, 91); \n"
"}")
        self.btn_select_photo.setFlat(True)
        self.btn_select_photo.setObjectName("btn_select_photo")
        self.horizontalLayout_2.addWidget(self.btn_select_photo)
        self.lbl_photo_name = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_photo_name.setFont(font)
        self.lbl_photo_name.setStyleSheet("color: rgb(137, 218, 199);\n"
"padding-left: 10px;\n"
"border: 3px solid rgb(43, 72, 101);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.lbl_photo_name.setText("")
        self.lbl_photo_name.setWordWrap(True)
        self.lbl_photo_name.setObjectName("lbl_photo_name")
        self.horizontalLayout_2.addWidget(self.lbl_photo_name)
        self.gridLayout_3.addWidget(self.frame, 3, 0, 1, 3)
        self.frame_5 = QtWidgets.QFrame(self.middle_frame)
        self.frame_5.setMinimumSize(QtCore.QSize(630, 179))
        self.frame_5.setMaximumSize(QtCore.QSize(491, 142))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_audio = QtWidgets.QLabel(self.frame_5)
        self.lbl_audio.setMinimumSize(QtCore.QSize(371, 47))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_audio.setFont(font)
        self.lbl_audio.setStyleSheet("color: rgb(137, 218, 199);\n"
"padding-left: 10px;\n"
"border: 3px solid rgb(43, 72, 101);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.lbl_audio.setText("")
        self.lbl_audio.setWordWrap(True)
        self.lbl_audio.setObjectName("lbl_audio")
        self.gridLayout.addWidget(self.lbl_audio, 0, 1, 1, 1)
        self.btn_select_audio = QtWidgets.QPushButton(self.frame_5)
        self.btn_select_audio.setMinimumSize(QtCore.QSize(200, 50))
        self.btn_select_audio.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(11)
        self.btn_select_audio.setFont(font)
        self.btn_select_audio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_select_audio.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(43, 72, 101);\n"
"border-radius: 10px;\n"
"background-color:  rgb(43, 72, 101);\n"
"color: rgb(137, 218, 199)\n"
"}\n"
"\n"
"QPushButton::hover:!pressed {\n"
"background-color: rgb(0, 43, 91);\n"
"border: 3px solid rgb(0, 43, 91); \n"
"}")
        self.btn_select_audio.setFlat(True)
        self.btn_select_audio.setObjectName("btn_select_audio")
        self.gridLayout.addWidget(self.btn_select_audio, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setMinimumSize(QtCore.QSize(610, 17))
        self.frame_4.setMaximumSize(QtCore.QSize(465, 72))
        self.frame_4.setStyleSheet("border: none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_or = QtWidgets.QLabel(self.frame_4)
        self.lbl_or.setMinimumSize(QtCore.QSize(81, 45))
        self.lbl_or.setMaximumSize(QtCore.QSize(81, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_or.setFont(font)
        self.lbl_or.setStyleSheet("color: rgb(137, 218, 199);")
        self.lbl_or.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_or.setObjectName("lbl_or")
        self.horizontalLayout_4.addWidget(self.lbl_or)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 2)
        self.btn_record_audio = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_record_audio.sizePolicy().hasHeightForWidth())
        self.btn_record_audio.setSizePolicy(sizePolicy)
        self.btn_record_audio.setMinimumSize(QtCore.QSize(610, 50))
        self.btn_record_audio.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(11)
        self.btn_record_audio.setFont(font)
        self.btn_record_audio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_record_audio.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(43, 72, 101);\n"
"border-radius: 10px;\n"
"background-color:  rgb(43, 72, 101);\n"
"color: rgb(137, 218, 199)\n"
"}\n"
"\n"
"QPushButton::hover:!pressed {\n"
"background-color: rgb(0, 43, 91);\n"
"border: 3px solid rgb(0, 43, 91); \n"
"}")
        self.btn_record_audio.setFlat(True)
        self.btn_record_audio.setObjectName("btn_record_audio")
        self.gridLayout.addWidget(self.btn_record_audio, 2, 0, 1, 2)
        self.gridLayout_3.addWidget(self.frame_5, 4, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(212, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 5, 0, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(212, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 5, 2, 2, 1)
        self.btn_submit = QtWidgets.QPushButton(self.middle_frame)
        self.btn_submit.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        self.btn_submit.setFont(font)
        self.btn_submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_submit.setStyleSheet("QPushButton {\n"
"border: 3px solid rgb(43, 72, 101);\n"
"border-radius: 10px;\n"
"background-color:  #002B5B;\n"
"color: rgb(137, 218, 199)\n"
"}\n"
"\n"
"QPushButton::hover:!pressed {\n"
"background-color: rgb(43, 72, 101);\n"
"border: 3px solid rgb(0, 43, 91); \n"
"}")
        self.btn_submit.setFlat(True)
        self.btn_submit.setObjectName("btn_submit")
        self.gridLayout_3.addWidget(self.btn_submit, 6, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 7, 1, 1, 1)
        self.lbl_lsn_cat_status = QtWidgets.QLabel(self.middle_frame)
        self.lbl_lsn_cat_status.setMinimumSize(QtCore.QSize(481, 41))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        self.lbl_lsn_cat_status.setFont(font)
        self.lbl_lsn_cat_status.setStyleSheet("border: 2px solid  rgb(0, 43, 91);\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(137, 218, 199);")
        self.lbl_lsn_cat_status.setText("")
        self.lbl_lsn_cat_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lsn_cat_status.setObjectName("lbl_lsn_cat_status")
        self.gridLayout_3.addWidget(self.lbl_lsn_cat_status, 8, 0, 1, 3)
        self.gridLayout_2.addWidget(self.middle_frame, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_heading.setText(_translate("Form", "মডিউলের কন্টেন্ট যুক্ত করুন"))
        self.lbl_category.setText(_translate("Form", "ক্যাটেগরি"))
        self.cmb_category.setItemText(0, _translate("Form", "ক্যাটাগরি নির্বাচন করুন"))
        self.cmb_category.setItemText(1, _translate("Form", "নাম শিখন (Noun)"))
        self.cmb_category.setItemText(2, _translate("Form", "ক্রিয়া শিখন (Verb)"))
        self.cmb_category.setItemText(3, _translate("Form", "সম্পর্ক শিখন (Association)"))
        self.cmb_category.setItemText(4, _translate("Form", "কর্মধারা শিখন (Activity)"))
        self.lbl_lesson_id.setText(_translate("Form", "পাঠ্যক্রম"))
        self.edit_lesson_id.setPlaceholderText(_translate("Form", "যেমনঃ ১"))
        self.lbl_lesson_topic.setText(_translate("Form", "পাঠ্যের বিষয়"))
        self.edit_lesson_topic.setPlaceholderText(_translate("Form", "যেমনঃ আম "))
        self.btn_select_photo.setText(_translate("Form", "ছবি/ভিডিও নির্বাচন করুন"))
        self.btn_select_photo.setShortcut(_translate("Form", "Return"))
        self.btn_select_audio.setText(_translate("Form", "অডিও নির্বাচন করুন"))
        self.btn_select_audio.setShortcut(_translate("Form", "Return"))
        self.lbl_or.setText(_translate("Form", "অথবা"))
        self.btn_record_audio.setText(_translate("Form", "অডিও রেকর্ড করুন"))
        self.btn_record_audio.setShortcut(_translate("Form", "Return"))
        self.btn_submit.setText(_translate("Form", "মডিউল তৈরি করুন "))
        self.btn_submit.setShortcut(_translate("Form", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
