# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Frontend\PyQt_UI\HomePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setMinimumSize(QtCore.QSize(0, 680))
        self.home_page.setObjectName("home_page")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.home_page)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.home_frame = QtWidgets.QFrame(self.home_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_frame.sizePolicy().hasHeightForWidth())
        self.home_frame.setSizePolicy(sizePolicy)
        self.home_frame.setMinimumSize(QtCore.QSize(1280, 720))
        self.home_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.home_frame.setStyleSheet("background-color: rgb(0, 43, 91);")
        self.home_frame.setObjectName("home_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.home_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.frm_banner_pic = QtWidgets.QFrame(self.home_frame)
        self.frm_banner_pic.setMaximumSize(QtCore.QSize(1200, 200))
        self.frm_banner_pic.setStyleSheet("border: none;")
        self.frm_banner_pic.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_banner_pic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_banner_pic.setObjectName("frm_banner_pic")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frm_banner_pic)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_lbl_ban_picture = QtWidgets.QLabel(self.frm_banner_pic)
        self.home_lbl_ban_picture.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.home_lbl_ban_picture.setStyleSheet("border: none;")
        self.home_lbl_ban_picture.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.home_lbl_ban_picture.setText("")
        self.home_lbl_ban_picture.setPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/banner_logo.png"))
        self.home_lbl_ban_picture.setScaledContents(False)
        self.home_lbl_ban_picture.setAlignment(QtCore.Qt.AlignCenter)
        self.home_lbl_ban_picture.setObjectName("home_lbl_ban_picture")
        self.verticalLayout_2.addWidget(self.home_lbl_ban_picture)
        self.gridLayout.addWidget(self.frm_banner_pic, 1, 0, 1, 1)
        self.frm_button = QtWidgets.QFrame(self.home_frame)
        self.frm_button.setMinimumSize(QtCore.QSize(1080, 190))
        self.frm_button.setMaximumSize(QtCore.QSize(1270, 190))
        self.frm_button.setStyleSheet("")
        self.frm_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_button.setObjectName("frm_button")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frm_button)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.home_btn_student = QtWidgets.QPushButton(self.frm_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_btn_student.sizePolicy().hasHeightForWidth())
        self.home_btn_student.setSizePolicy(sizePolicy)
        self.home_btn_student.setMinimumSize(QtCore.QSize(160, 150))
        self.home_btn_student.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.home_btn_student.setFont(font)
        self.home_btn_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn_student.setMouseTracking(True)
        self.home_btn_student.setAcceptDrops(True)
        self.home_btn_student.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.383, y1:0.727, x2:1, y2:0, stop:0 rgba(49, 181, 148, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 4px solid qlineargradient(spread:pad, x1:0.716905, y1:0.347, x2:0, y2:1, stop:0 rgba(26, 181, 219, 255), stop:1 rgba(255, 255, 255, 255)) ;\n"
"    border-radius: 15px;\n"
"    margin: 10px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"     border: 4px solid qlineargradient(spread:pad, x1:0.338, y1:0.602273, x2:1, y2:0, stop:0 rgba(26, 181, 219, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0.606965, y1:0.409, x2:0, y2:1, stop:0 rgba(81, 181, 159, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.home_btn_student.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/reg_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_student.setIcon(icon)
        self.home_btn_student.setIconSize(QtCore.QSize(250, 300))
        self.home_btn_student.setFlat(False)
        self.home_btn_student.setObjectName("home_btn_student")
        self.horizontalLayout_2.addWidget(self.home_btn_student)
        self.home_btn_lesson = QtWidgets.QPushButton(self.frm_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_btn_lesson.sizePolicy().hasHeightForWidth())
        self.home_btn_lesson.setSizePolicy(sizePolicy)
        self.home_btn_lesson.setMinimumSize(QtCore.QSize(160, 150))
        self.home_btn_lesson.setMaximumSize(QtCore.QSize(200, 200))
        self.home_btn_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn_lesson.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.383, y1:0.727, x2:1, y2:0, stop:0 rgba(49, 181, 148, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 4px solid qlineargradient(spread:pad, x1:0.716905, y1:0.347, x2:0, y2:1, stop:0 rgba(26, 181, 219, 255), stop:1 rgba(255, 255, 255, 255)) ;\n"
"    border-radius: 15px;\n"
"    margin: 10px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"     border: 4px solid qlineargradient(spread:pad, x1:0.338, y1:0.602273, x2:1, y2:0, stop:0 rgba(26, 181, 219, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0.606965, y1:0.409, x2:0, y2:1, stop:0 rgba(81, 181, 159, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.home_btn_lesson.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/std_lsn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_lesson.setIcon(icon1)
        self.home_btn_lesson.setIconSize(QtCore.QSize(250, 300))
        self.home_btn_lesson.setObjectName("home_btn_lesson")
        self.horizontalLayout_2.addWidget(self.home_btn_lesson)
        self.home_btn_quiz = QtWidgets.QPushButton(self.frm_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_btn_quiz.sizePolicy().hasHeightForWidth())
        self.home_btn_quiz.setSizePolicy(sizePolicy)
        self.home_btn_quiz.setMinimumSize(QtCore.QSize(160, 150))
        self.home_btn_quiz.setMaximumSize(QtCore.QSize(200, 200))
        self.home_btn_quiz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn_quiz.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.383, y1:0.727, x2:1, y2:0, stop:0 rgba(49, 181, 148, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 4px solid qlineargradient(spread:pad, x1:0.716905, y1:0.347, x2:0, y2:1, stop:0 rgba(26, 181, 219, 255), stop:1 rgba(255, 255, 255, 255)) ;\n"
"    border-radius: 15px;\n"
"    margin: 10px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"     border: 4px solid qlineargradient(spread:pad, x1:0.338, y1:0.602273, x2:1, y2:0, stop:0 rgba(26, 181, 219, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0.606965, y1:0.409, x2:0, y2:1, stop:0 rgba(81, 181, 159, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.home_btn_quiz.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/std_assessment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_quiz.setIcon(icon2)
        self.home_btn_quiz.setIconSize(QtCore.QSize(250, 300))
        self.home_btn_quiz.setObjectName("home_btn_quiz")
        self.horizontalLayout_2.addWidget(self.home_btn_quiz)
        self.home_btn_progress = QtWidgets.QPushButton(self.frm_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_btn_progress.sizePolicy().hasHeightForWidth())
        self.home_btn_progress.setSizePolicy(sizePolicy)
        self.home_btn_progress.setMinimumSize(QtCore.QSize(160, 150))
        self.home_btn_progress.setMaximumSize(QtCore.QSize(200, 200))
        self.home_btn_progress.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn_progress.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.383, y1:0.727, x2:1, y2:0, stop:0 rgba(49, 181, 148, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 4px solid qlineargradient(spread:pad, x1:0.716905, y1:0.347, x2:0, y2:1, stop:0 rgba(26, 181, 219, 255), stop:1 rgba(255, 255, 255, 255)) ;\n"
"    border-radius: 15px;\n"
"    margin: 10px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"     border: 4px solid qlineargradient(spread:pad, x1:0.338, y1:0.602273, x2:1, y2:0, stop:0 rgba(26, 181, 219, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0.606965, y1:0.409, x2:0, y2:1, stop:0 rgba(81, 181, 159, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.home_btn_progress.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/std_perfor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_progress.setIcon(icon3)
        self.home_btn_progress.setIconSize(QtCore.QSize(250, 300))
        self.home_btn_progress.setObjectName("home_btn_progress")
        self.horizontalLayout_2.addWidget(self.home_btn_progress)
        self.home_btn_settings = QtWidgets.QPushButton(self.frm_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_btn_settings.sizePolicy().hasHeightForWidth())
        self.home_btn_settings.setSizePolicy(sizePolicy)
        self.home_btn_settings.setMinimumSize(QtCore.QSize(160, 150))
        self.home_btn_settings.setMaximumSize(QtCore.QSize(200, 200))
        self.home_btn_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn_settings.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.383, y1:0.727, x2:1, y2:0, stop:0 rgba(49, 181, 148, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 4px solid qlineargradient(spread:pad, x1:0.716905, y1:0.347, x2:0, y2:1, stop:0 rgba(26, 181, 219, 255), stop:1 rgba(255, 255, 255, 255)) ;\n"
"    border-radius: 15px;\n"
"    margin: 10px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"     border: 4px solid qlineargradient(spread:pad, x1:0.338, y1:0.602273, x2:1, y2:0, stop:0 rgba(26, 181, 219, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0.606965, y1:0.409, x2:0, y2:1, stop:0 rgba(81, 181, 159, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.home_btn_settings.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/setting_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_settings.setIcon(icon4)
        self.home_btn_settings.setIconSize(QtCore.QSize(250, 300))
        self.home_btn_settings.setObjectName("home_btn_settings")
        self.horizontalLayout_2.addWidget(self.home_btn_settings)
        self.gridLayout.addWidget(self.frm_button, 3, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.home_frame)
        self.stackedWidget.addWidget(self.home_page)
        self.student_page = QtWidgets.QWidget()
        self.student_page.setMinimumSize(QtCore.QSize(1280, 720))
        self.student_page.setObjectName("student_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.student_page)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.student_frame = QtWidgets.QFrame(self.student_page)
        self.student_frame.setMinimumSize(QtCore.QSize(1280, 720))
        self.student_frame.setStyleSheet("border-radius: 0;")
        self.student_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.student_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.student_frame.setObjectName("student_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.student_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame = QtWidgets.QFrame(self.student_frame)
        self.top_frame.setMinimumSize(QtCore.QSize(1251, 91))
        self.top_frame.setStyleSheet("background-color: #2B4865;")
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.std_btn_back_to_home = QtWidgets.QPushButton(self.top_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.std_btn_back_to_home.sizePolicy().hasHeightForWidth())
        self.std_btn_back_to_home.setSizePolicy(sizePolicy)
        self.std_btn_back_to_home.setMinimumSize(QtCore.QSize(0, 60))
        self.std_btn_back_to_home.setMaximumSize(QtCore.QSize(60, 60))
        self.std_btn_back_to_home.setBaseSize(QtCore.QSize(0, 4))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.std_btn_back_to_home.setFont(font)
        self.std_btn_back_to_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.std_btn_back_to_home.setMouseTracking(True)
        self.std_btn_back_to_home.setStyleSheet("QPushButton {\n"
"    background-color: #2B4865 #256D85;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color:  #256D85;\n"
"    border-radius: 30px;\n"
"}")
        self.std_btn_back_to_home.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/back_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.std_btn_back_to_home.setIcon(icon5)
        self.std_btn_back_to_home.setIconSize(QtCore.QSize(200, 200))
        self.std_btn_back_to_home.setAutoDefault(False)
        self.std_btn_back_to_home.setDefault(False)
        self.std_btn_back_to_home.setFlat(False)
        self.std_btn_back_to_home.setObjectName("std_btn_back_to_home")
        self.horizontalLayout_4.addWidget(self.std_btn_back_to_home)
        self.std_lbl_headline = QtWidgets.QLabel(self.top_frame)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(27)
        self.std_lbl_headline.setFont(font)
        self.std_lbl_headline.setStyleSheet("color: #8FE3CF")
        self.std_lbl_headline.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.std_lbl_headline.setObjectName("std_lbl_headline")
        self.horizontalLayout_4.addWidget(self.std_lbl_headline)
        self.verticalLayout.addWidget(self.top_frame)
        self.mid_frame = QtWidgets.QFrame(self.student_frame)
        self.mid_frame.setMinimumSize(QtCore.QSize(1251, 661))
        self.mid_frame.setStyleSheet("background-color: rgb(255, 220, 243);")
        self.mid_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mid_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mid_frame.setObjectName("mid_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.mid_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.std_tableWidget = QtWidgets.QTableWidget(self.mid_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.std_tableWidget.setFont(font)
        self.std_tableWidget.setStyleSheet("QHeaderView::section {\n"
"    background-color: #002B5B;\n"
"    color: rgb(143, 227, 207);\n"
"}\n"
"\n"
"\n"
"\n"
"QTableWidget {\n"
"    background-color: #256D85;\n"
"    gridline-color: rgb(255, 255, 255);\n"
"    color: #fff;\n"
"}\n"
"\n"
"")
        self.std_tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.std_tableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.std_tableWidget.setLineWidth(1)
        self.std_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.std_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.std_tableWidget.setAlternatingRowColors(False)
        self.std_tableWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.std_tableWidget.setShowGrid(True)
        self.std_tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.std_tableWidget.setCornerButtonEnabled(True)
        self.std_tableWidget.setRowCount(0)
        self.std_tableWidget.setColumnCount(6)
        self.std_tableWidget.setObjectName("std_tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        item.setFont(font)
        self.std_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        item.setFont(font)
        self.std_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        item.setFont(font)
        self.std_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        item.setFont(font)
        self.std_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        item.setFont(font)
        self.std_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(13)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        self.std_tableWidget.setHorizontalHeaderItem(5, item)
        self.std_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.std_tableWidget.horizontalHeader().setDefaultSectionSize(170)
        self.std_tableWidget.horizontalHeader().setHighlightSections(True)
        self.std_tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.std_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.std_tableWidget.verticalHeader().setVisible(False)
        self.std_tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.std_tableWidget.verticalHeader().setDefaultSectionSize(35)
        self.std_tableWidget.verticalHeader().setMinimumSectionSize(29)
        self.horizontalLayout_5.addWidget(self.std_tableWidget)
        self.verticalLayout.addWidget(self.mid_frame)
        self.bottom_frame = QtWidgets.QFrame(self.student_frame)
        self.bottom_frame.setMinimumSize(QtCore.QSize(1251, 83))
        self.bottom_frame.setStyleSheet("background-color: rgb(42, 70, 98);")
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.std_btn_add_student = QtWidgets.QPushButton(self.bottom_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(230)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.std_btn_add_student.sizePolicy().hasHeightForWidth())
        self.std_btn_add_student.setSizePolicy(sizePolicy)
        self.std_btn_add_student.setMinimumSize(QtCore.QSize(251, 41))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.std_btn_add_student.setFont(font)
        self.std_btn_add_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.std_btn_add_student.setStyleSheet("QPushButton {\n"
"background-color: rgb(160, 253, 230);\n"
"color:  #256D85 ;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    \n"
"    background-color: rgb(143, 227, 207);\n"
"    color: #2B4865;\n"
"\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/add_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.std_btn_add_student.setIcon(icon6)
        self.std_btn_add_student.setIconSize(QtCore.QSize(25, 25))
        self.std_btn_add_student.setObjectName("std_btn_add_student")
        self.horizontalLayout_6.addWidget(self.std_btn_add_student)
        spacerItem3 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.std_btn_update_info = QtWidgets.QPushButton(self.bottom_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(230)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.std_btn_update_info.sizePolicy().hasHeightForWidth())
        self.std_btn_update_info.setSizePolicy(sizePolicy)
        self.std_btn_update_info.setMinimumSize(QtCore.QSize(290, 40))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.std_btn_update_info.setFont(font)
        self.std_btn_update_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.std_btn_update_info.setStyleSheet("QPushButton {\n"
"background-color: rgb(160, 253, 230);\n"
"color:  #256D85 ;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    \n"
"    background-color: rgb(143, 227, 207);\n"
"    color: #2B4865;\n"
"\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/edit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.std_btn_update_info.setIcon(icon7)
        self.std_btn_update_info.setIconSize(QtCore.QSize(20, 25))
        self.std_btn_update_info.setObjectName("std_btn_update_info")
        self.horizontalLayout_6.addWidget(self.std_btn_update_info)
        spacerItem4 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.std_btn_remove_student = QtWidgets.QPushButton(self.bottom_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(230)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.std_btn_remove_student.sizePolicy().hasHeightForWidth())
        self.std_btn_remove_student.setSizePolicy(sizePolicy)
        self.std_btn_remove_student.setMinimumSize(QtCore.QSize(260, 40))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        self.std_btn_remove_student.setFont(font)
        self.std_btn_remove_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.std_btn_remove_student.setStyleSheet("QPushButton {\n"
"background-color: rgb(160, 253, 230);\n"
"color:  #256D85 ;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    \n"
"    background-color: rgb(143, 227, 207);\n"
"    color: #2B4865;\n"
"\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/trash_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.std_btn_remove_student.setIcon(icon8)
        self.std_btn_remove_student.setObjectName("std_btn_remove_student")
        self.horizontalLayout_6.addWidget(self.std_btn_remove_student)
        spacerItem5 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.bottom_frame)
        self.horizontalLayout.addWidget(self.student_frame)
        self.stackedWidget.addWidget(self.student_page)
        self.lesson_page = QtWidgets.QWidget()
        self.lesson_page.setObjectName("lesson_page")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.lesson_page)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lesson_frame = QtWidgets.QFrame(self.lesson_page)
        self.lesson_frame.setMinimumSize(QtCore.QSize(1280, 720))
        self.lesson_frame.setStyleSheet("")
        self.lesson_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lesson_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lesson_frame.setObjectName("lesson_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.lesson_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.top_frame_2 = QtWidgets.QFrame(self.lesson_frame)
        self.top_frame_2.setMinimumSize(QtCore.QSize(1180, 80))
        self.top_frame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.top_frame_2.setStyleSheet("background-color: #2B4865;")
        self.top_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_2.setObjectName("top_frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.top_frame_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lsn_btn_back_to_home = QtWidgets.QPushButton(self.top_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lsn_btn_back_to_home.sizePolicy().hasHeightForWidth())
        self.lsn_btn_back_to_home.setSizePolicy(sizePolicy)
        self.lsn_btn_back_to_home.setMinimumSize(QtCore.QSize(0, 60))
        self.lsn_btn_back_to_home.setMaximumSize(QtCore.QSize(60, 60))
        self.lsn_btn_back_to_home.setBaseSize(QtCore.QSize(0, 4))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lsn_btn_back_to_home.setFont(font)
        self.lsn_btn_back_to_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lsn_btn_back_to_home.setMouseTracking(True)
        self.lsn_btn_back_to_home.setStyleSheet("QPushButton {\n"
"    background-color: #2B4865 #256D85;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color:  #256D85;\n"
"    border-radius: 30px;\n"
"}")
        self.lsn_btn_back_to_home.setText("")
        self.lsn_btn_back_to_home.setIcon(icon5)
        self.lsn_btn_back_to_home.setIconSize(QtCore.QSize(200, 200))
        self.lsn_btn_back_to_home.setAutoDefault(False)
        self.lsn_btn_back_to_home.setDefault(False)
        self.lsn_btn_back_to_home.setFlat(False)
        self.lsn_btn_back_to_home.setObjectName("lsn_btn_back_to_home")
        self.horizontalLayout_7.addWidget(self.lsn_btn_back_to_home)
        self.lsn_lbl_headline = QtWidgets.QLabel(self.top_frame_2)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(27)
        self.lsn_lbl_headline.setFont(font)
        self.lsn_lbl_headline.setStyleSheet("color: #8FE3CF")
        self.lsn_lbl_headline.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lsn_lbl_headline.setObjectName("lsn_lbl_headline")
        self.horizontalLayout_7.addWidget(self.lsn_lbl_headline)
        self.gridLayout_2.addWidget(self.top_frame_2, 0, 0, 1, 1)
        self.mid_frame_2 = QtWidgets.QFrame(self.lesson_frame)
        self.mid_frame_2.setMinimumSize(QtCore.QSize(1180, 520))
        self.mid_frame_2.setStyleSheet("background-color:rgb(36, 105, 127);")
        self.mid_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mid_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mid_frame_2.setObjectName("mid_frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mid_frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bottom_top_frame = QtWidgets.QFrame(self.mid_frame_2)
        self.bottom_top_frame.setMinimumSize(QtCore.QSize(0, 60))
        self.bottom_top_frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.bottom_top_frame.setStyleSheet("background-color: rgb(36, 105, 127);\n"
"color: rgb(137, 218, 199);\n"
"")
        self.bottom_top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_top_frame.setObjectName("bottom_top_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.bottom_top_frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(141, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.lsn_lbl_category = QtWidgets.QLabel(self.bottom_top_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lsn_lbl_category.setFont(font)
        self.lsn_lbl_category.setAlignment(QtCore.Qt.AlignCenter)
        self.lsn_lbl_category.setObjectName("lsn_lbl_category")
        self.horizontalLayout_8.addWidget(self.lsn_lbl_category)
        self.lsn_cmb_category = QtWidgets.QComboBox(self.bottom_top_frame)
        self.lsn_cmb_category.setMinimumSize(QtCore.QSize(280, 40))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lsn_cmb_category.setFont(font)
        self.lsn_cmb_category.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lsn_cmb_category.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"padding-left: 15px;\n"
"border-radius: 10px;\n"
"color: rgb(43, 72, 101);")
        self.lsn_cmb_category.setObjectName("lsn_cmb_category")
        self.lsn_cmb_category.addItem("")
        self.lsn_cmb_category.addItem("")
        self.lsn_cmb_category.addItem("")
        self.lsn_cmb_category.addItem("")
        self.lsn_cmb_category.addItem("")
        self.horizontalLayout_8.addWidget(self.lsn_cmb_category)
        spacerItem7 = QtWidgets.QSpacerItem(143, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.lsn_lbl_lessons = QtWidgets.QLabel(self.bottom_top_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lsn_lbl_lessons.setFont(font)
        self.lsn_lbl_lessons.setAlignment(QtCore.Qt.AlignCenter)
        self.lsn_lbl_lessons.setObjectName("lsn_lbl_lessons")
        self.horizontalLayout_8.addWidget(self.lsn_lbl_lessons)
        self.lsn_cmb_lessons = QtWidgets.QComboBox(self.bottom_top_frame)
        self.lsn_cmb_lessons.setMinimumSize(QtCore.QSize(280, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lsn_cmb_lessons.setFont(font)
        self.lsn_cmb_lessons.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lsn_cmb_lessons.setStyleSheet("background-color: rgb(137, 218, 199);\n"
"border-radius: 12px;\n"
"color: rgb(0, 43, 91);\n"
"padding-left: 10px;")
        self.lsn_cmb_lessons.setObjectName("lsn_cmb_lessons")
        self.lsn_cmb_lessons.addItem("")
        self.horizontalLayout_8.addWidget(self.lsn_cmb_lessons)
        spacerItem8 = QtWidgets.QSpacerItem(141, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_4.addWidget(self.bottom_top_frame)
        self.middle_content_frame = QtWidgets.QFrame(self.mid_frame_2)
        self.middle_content_frame.setMinimumSize(QtCore.QSize(1241, 400))
        self.middle_content_frame.setStyleSheet("background-color: rgb(36, 105, 127)")
        self.middle_content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.middle_content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middle_content_frame.setObjectName("middle_content_frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.middle_content_frame)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.mediaStackWidget = QtWidgets.QStackedWidget(self.middle_content_frame)
        self.mediaStackWidget.setMinimumSize(QtCore.QSize(690, 400))
        self.mediaStackWidget.setObjectName("mediaStackWidget")
        self.image_page = QtWidgets.QWidget()
        self.image_page.setObjectName("image_page")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.image_page)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lsn_lbl_lesson_image = QtWidgets.QLabel(self.image_page)
        self.lsn_lbl_lesson_image.setMinimumSize(QtCore.QSize(690, 380))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lsn_lbl_lesson_image.setFont(font)
        self.lsn_lbl_lesson_image.setStyleSheet("border: 3px dotted  rgb(137, 218, 199);\n"
"color: rgb(137, 218, 199);")
        self.lsn_lbl_lesson_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lsn_lbl_lesson_image.setObjectName("lsn_lbl_lesson_image")
        self.horizontalLayout_9.addWidget(self.lsn_lbl_lesson_image)
        self.mediaStackWidget.addWidget(self.image_page)
        self.video_page = QtWidgets.QWidget()
        self.video_page.setObjectName("video_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.video_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.video_player_widget = QtWidgets.QHBoxLayout()
        self.video_player_widget.setObjectName("video_player_widget")
        self.verticalLayout_5.addLayout(self.video_player_widget)
        self.mediaStackWidget.addWidget(self.video_page)
        self.horizontalLayout_12.addWidget(self.mediaStackWidget)
        self.lsn_lbl_lesson_topic = QtWidgets.QLabel(self.middle_content_frame)
        self.lsn_lbl_lesson_topic.setMinimumSize(QtCore.QSize(520, 400))
        self.lsn_lbl_lesson_topic.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lsn_lbl_lesson_topic.setFont(font)
        self.lsn_lbl_lesson_topic.setStyleSheet("border: 3px dotted  rgb(137, 218, 199);\n"
"color: rgb(137, 218, 199);")
        self.lsn_lbl_lesson_topic.setAlignment(QtCore.Qt.AlignCenter)
        self.lsn_lbl_lesson_topic.setWordWrap(True)
        self.lsn_lbl_lesson_topic.setObjectName("lsn_lbl_lesson_topic")
        self.horizontalLayout_12.addWidget(self.lsn_lbl_lesson_topic)
        self.verticalLayout_4.addWidget(self.middle_content_frame)
        self.gridLayout_2.addWidget(self.mid_frame_2, 1, 0, 1, 1)
        self.bottom_frame_2 = QtWidgets.QFrame(self.lesson_frame)
        self.bottom_frame_2.setMinimumSize(QtCore.QSize(1180, 71))
        self.bottom_frame_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.bottom_frame_2.setStyleSheet("background-color: rgb(42, 70, 98);\n"
"")
        self.bottom_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame_2.setObjectName("bottom_frame_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.bottom_frame_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lsn_btn_add_lessons = QtWidgets.QPushButton(self.bottom_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(230)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.lsn_btn_add_lessons.sizePolicy().hasHeightForWidth())
        self.lsn_btn_add_lessons.setSizePolicy(sizePolicy)
        self.lsn_btn_add_lessons.setMinimumSize(QtCore.QSize(250, 50))
        self.lsn_btn_add_lessons.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lsn_btn_add_lessons.setFont(font)
        self.lsn_btn_add_lessons.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lsn_btn_add_lessons.setStyleSheet("QPushButton {\n"
"background-color: rgb(160, 253, 230);\n"
"color:  #256D85 ;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover:!pressed {\n"
"    \n"
"    background-color: rgb(143, 227, 207);\n"
"    color: #2B4865;\n"
"\n"
"}")
        self.lsn_btn_add_lessons.setIcon(icon6)
        self.lsn_btn_add_lessons.setIconSize(QtCore.QSize(30, 40))
        self.lsn_btn_add_lessons.setObjectName("lsn_btn_add_lessons")
        self.horizontalLayout_10.addWidget(self.lsn_btn_add_lessons)
        self.gridLayout_2.addWidget(self.bottom_frame_2, 2, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.lesson_frame)
        self.stackedWidget.addWidget(self.lesson_page)
        self.task_page = QtWidgets.QWidget()
        self.task_page.setObjectName("task_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.task_page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.evaluation_frame = QtWidgets.QFrame(self.task_page)
        self.evaluation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.evaluation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.evaluation_frame.setObjectName("evaluation_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.evaluation_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top_frame_3 = QtWidgets.QFrame(self.evaluation_frame)
        self.top_frame_3.setMinimumSize(QtCore.QSize(1180, 80))
        self.top_frame_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.top_frame_3.setStyleSheet("background-color: #2B4865;")
        self.top_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_3.setObjectName("top_frame_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.top_frame_3)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.task_btn_back_to_home = QtWidgets.QPushButton(self.top_frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_btn_back_to_home.sizePolicy().hasHeightForWidth())
        self.task_btn_back_to_home.setSizePolicy(sizePolicy)
        self.task_btn_back_to_home.setMinimumSize(QtCore.QSize(0, 60))
        self.task_btn_back_to_home.setMaximumSize(QtCore.QSize(60, 60))
        self.task_btn_back_to_home.setBaseSize(QtCore.QSize(0, 4))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.task_btn_back_to_home.setFont(font)
        self.task_btn_back_to_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.task_btn_back_to_home.setMouseTracking(True)
        self.task_btn_back_to_home.setStyleSheet("QPushButton {\n"
"    background-color: #2B4865 #256D85;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color:  #256D85;\n"
"    border-radius: 30px;\n"
"}")
        self.task_btn_back_to_home.setText("")
        self.task_btn_back_to_home.setIcon(icon5)
        self.task_btn_back_to_home.setIconSize(QtCore.QSize(200, 200))
        self.task_btn_back_to_home.setAutoDefault(False)
        self.task_btn_back_to_home.setDefault(False)
        self.task_btn_back_to_home.setFlat(False)
        self.task_btn_back_to_home.setObjectName("task_btn_back_to_home")
        self.horizontalLayout_13.addWidget(self.task_btn_back_to_home)
        self.lsn_lbl_headline_2 = QtWidgets.QLabel(self.top_frame_3)
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(27)
        self.lsn_lbl_headline_2.setFont(font)
        self.lsn_lbl_headline_2.setStyleSheet("color: #8FE3CF")
        self.lsn_lbl_headline_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lsn_lbl_headline_2.setObjectName("lsn_lbl_headline_2")
        self.horizontalLayout_13.addWidget(self.lsn_lbl_headline_2)
        self.verticalLayout_3.addWidget(self.top_frame_3)
        self.body = QtWidgets.QFrame(self.evaluation_frame)
        self.body.setStyleSheet("background-color: rgb(37, 109, 133);")
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.eval_left_frame = QtWidgets.QFrame(self.body)
        self.eval_left_frame.setMinimumSize(QtCore.QSize(385, 636))
        self.eval_left_frame.setStyleSheet("")
        self.eval_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.eval_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.eval_left_frame.setObjectName("eval_left_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.eval_left_frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(20, 164, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 1, 0, 1, 1)
        self.task_btn_mcq = QtWidgets.QPushButton(self.eval_left_frame)
        self.task_btn_mcq.setMinimumSize(QtCore.QSize(261, 61))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.task_btn_mcq.setFont(font)
        self.task_btn_mcq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.task_btn_mcq.setStyleSheet("QPushButton {\n"
"background-color: rgb(160, 253, 230);\n"
"color:  rgb(0, 43, 91) ;\n"
"border-radius: 15px;\n"
"border: 4px solid rgb(43, 72, 101);\n"
"}\n"
"\n"
"QPushButton::hover:!pressed {\n"
"    \n"
"    background-color: rgb(143, 227, 207);\n"
"    color: rgb(0, 43, 91);\n"
"\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/mcq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.task_btn_mcq.setIcon(icon9)
        self.task_btn_mcq.setIconSize(QtCore.QSize(25, 50))
        self.task_btn_mcq.setObjectName("task_btn_mcq")
        self.gridLayout_5.addWidget(self.task_btn_mcq, 1, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem11, 1, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem12, 2, 0, 1, 1)
        self.task_btn_matching = QtWidgets.QPushButton(self.eval_left_frame)
        self.task_btn_matching.setMinimumSize(QtCore.QSize(261, 61))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.task_btn_matching.setFont(font)
        self.task_btn_matching.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.task_btn_matching.setStyleSheet("QPushButton {\n"
"background-color: rgb(160, 253, 230);\n"
"color:  rgb(0, 43, 91) ;\n"
"border-radius: 15px;\n"
"border: 4px solid rgb(43, 72, 101);\n"
"}\n"
"\n"
"QPushButton::hover:!pressed {\n"
"    \n"
"    background-color: rgb(143, 227, 207);\n"
"    color: rgb(0, 43, 91);\n"
"\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/connect_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.task_btn_matching.setIcon(icon10)
        self.task_btn_matching.setIconSize(QtCore.QSize(28, 50))
        self.task_btn_matching.setObjectName("task_btn_matching")
        self.gridLayout_5.addWidget(self.task_btn_matching, 2, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem13, 2, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem14, 3, 0, 1, 1)
        self.task_btn_sequence = QtWidgets.QPushButton(self.eval_left_frame)
        self.task_btn_sequence.setMinimumSize(QtCore.QSize(261, 61))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.task_btn_sequence.setFont(font)
        self.task_btn_sequence.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.task_btn_sequence.setStyleSheet("QPushButton {\n"
"background-color: rgb(160, 253, 230);\n"
"color:  rgb(0, 43, 91) ;\n"
"border-radius: 15px;\n"
"border: 4px solid rgb(43, 72, 101);\n"
"}\n"
"\n"
"QPushButton::hover:!pressed {\n"
"    \n"
"    background-color: rgb(143, 227, 207);\n"
"    color: rgb(0, 43, 91);\n"
"\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/sequence_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.task_btn_sequence.setIcon(icon11)
        self.task_btn_sequence.setIconSize(QtCore.QSize(26, 50))
        self.task_btn_sequence.setObjectName("task_btn_sequence")
        self.gridLayout_5.addWidget(self.task_btn_sequence, 3, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem15, 3, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem16, 4, 0, 1, 1)
        self.task_btn_puzzle = QtWidgets.QPushButton(self.eval_left_frame)
        self.task_btn_puzzle.setMinimumSize(QtCore.QSize(261, 61))
        font = QtGui.QFont()
        font.setFamily("Hind Siliguri Medium")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.task_btn_puzzle.setFont(font)
        self.task_btn_puzzle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.task_btn_puzzle.setStyleSheet("QPushButton {\n"
"background-color: rgb(160, 253, 230);\n"
"color:  rgb(0, 43, 91) ;\n"
"border-radius: 15px;\n"
"border: 4px solid rgb(43, 72, 101);\n"
"}\n"
"\n"
"QPushButton::hover:!pressed {\n"
"    \n"
"    background-color: rgb(143, 227, 207);\n"
"    color: rgb(0, 43, 91);\n"
"\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/puzzle_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.task_btn_puzzle.setIcon(icon12)
        self.task_btn_puzzle.setIconSize(QtCore.QSize(20, 30))
        self.task_btn_puzzle.setObjectName("task_btn_puzzle")
        self.gridLayout_5.addWidget(self.task_btn_puzzle, 4, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem17, 4, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 163, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem18, 5, 1, 1, 1)
        self.horizontalLayout_16.addWidget(self.eval_left_frame)
        self.eval_right_frame = QtWidgets.QFrame(self.body)
        self.eval_right_frame.setMinimumSize(QtCore.QSize(891, 621))
        self.eval_right_frame.setStyleSheet("")
        self.eval_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.eval_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.eval_right_frame.setObjectName("eval_right_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.eval_right_frame)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.evalstackwidget = QtWidgets.QStackedWidget(self.eval_right_frame)
        self.evalstackwidget.setObjectName("evalstackwidget")
        self.mcq_page = QtWidgets.QWidget()
        self.mcq_page.setObjectName("mcq_page")
        self.task_lbl_mcq = QtWidgets.QLabel(self.mcq_page)
        self.task_lbl_mcq.setGeometry(QtCore.QRect(20, 30, 841, 581))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.task_lbl_mcq.setFont(font)
        self.task_lbl_mcq.setStyleSheet("color: rgb(160, 253, 230);")
        self.task_lbl_mcq.setAlignment(QtCore.Qt.AlignCenter)
        self.task_lbl_mcq.setObjectName("task_lbl_mcq")
        self.evalstackwidget.addWidget(self.mcq_page)
        self.dragdrop_page = QtWidgets.QWidget()
        self.dragdrop_page.setObjectName("dragdrop_page")
        self.task_lbl_matching = QtWidgets.QLabel(self.dragdrop_page)
        self.task_lbl_matching.setGeometry(QtCore.QRect(30, 10, 841, 581))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.task_lbl_matching.setFont(font)
        self.task_lbl_matching.setStyleSheet("color: rgb(160, 253, 230);")
        self.task_lbl_matching.setAlignment(QtCore.Qt.AlignCenter)
        self.task_lbl_matching.setObjectName("task_lbl_matching")
        self.evalstackwidget.addWidget(self.dragdrop_page)
        self.sequence_page = QtWidgets.QWidget()
        self.sequence_page.setObjectName("sequence_page")
        self.task_lbl_sequencing = QtWidgets.QLabel(self.sequence_page)
        self.task_lbl_sequencing.setGeometry(QtCore.QRect(30, 40, 841, 581))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.task_lbl_sequencing.setFont(font)
        self.task_lbl_sequencing.setStyleSheet("color: rgb(160, 253, 230);")
        self.task_lbl_sequencing.setAlignment(QtCore.Qt.AlignCenter)
        self.task_lbl_sequencing.setObjectName("task_lbl_sequencing")
        self.evalstackwidget.addWidget(self.sequence_page)
        self.puzzle_page = QtWidgets.QWidget()
        self.puzzle_page.setObjectName("puzzle_page")
        self.task_lbl_puzzle = QtWidgets.QLabel(self.puzzle_page)
        self.task_lbl_puzzle.setGeometry(QtCore.QRect(20, 30, 841, 581))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.task_lbl_puzzle.setFont(font)
        self.task_lbl_puzzle.setStyleSheet("color: rgb(160, 253, 230);")
        self.task_lbl_puzzle.setAlignment(QtCore.Qt.AlignCenter)
        self.task_lbl_puzzle.setObjectName("task_lbl_puzzle")
        self.evalstackwidget.addWidget(self.puzzle_page)
        self.gridLayout_6.addWidget(self.evalstackwidget, 0, 0, 1, 1)
        self.horizontalLayout_16.addWidget(self.eval_right_frame)
        self.verticalLayout_3.addWidget(self.body)
        self.verticalLayout_7.addWidget(self.evaluation_frame)
        self.stackedWidget.addWidget(self.task_page)
        self.horizontalLayout_14.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.mediaStackWidget.setCurrentIndex(0)
        self.evalstackwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.std_lbl_headline.setText(_translate("MainWindow", "শিক্ষার্থীর তথ্যসমূহ "))
        self.std_tableWidget.setSortingEnabled(True)
        item = self.std_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "শিক্ষার্থীর আইডি"))
        item = self.std_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "শিক্ষার্থীর নাম"))
        item = self.std_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "শিক্ষার্থীর বয়স "))
        item = self.std_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ঠিকানা"))
        item = self.std_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "অভিভাবকের নাম"))
        item = self.std_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "অভিভাবকের মোবাইল নম্বর"))
        self.std_btn_add_student.setText(_translate("MainWindow", "নতুন শিক্ষার্থী যুক্ত করুন"))
        self.std_btn_update_info.setText(_translate("MainWindow", "শিক্ষার্থীর তথ্য আপডেট করুন"))
        self.std_btn_remove_student.setText(_translate("MainWindow", "শিক্ষার্থী এন্ট্রি বাতিল করুন"))
        self.lsn_lbl_headline.setText(_translate("MainWindow", "পাঠসূচি"))
        self.lsn_lbl_category.setText(_translate("MainWindow", "ক্যাটাগরি"))
        self.lsn_cmb_category.setCurrentText(_translate("MainWindow", "ক্যাটাগরি নির্বাচন করুন"))
        self.lsn_cmb_category.setItemText(0, _translate("MainWindow", "ক্যাটাগরি নির্বাচন করুন"))
        self.lsn_cmb_category.setItemText(1, _translate("MainWindow", "নাম শিখন (Noun)"))
        self.lsn_cmb_category.setItemText(2, _translate("MainWindow", "ক্রিয়া শিখন (Verb)"))
        self.lsn_cmb_category.setItemText(3, _translate("MainWindow", "সম্পর্ক শিখন (Association)"))
        self.lsn_cmb_category.setItemText(4, _translate("MainWindow", "কর্মধারা শিখন (Activity)"))
        self.lsn_lbl_lessons.setText(_translate("MainWindow", "পাঠসমূহ"))
        self.lsn_cmb_lessons.setItemText(0, _translate("MainWindow", "পাঠ ক্রম নির্বাচন করুন"))
        self.lsn_lbl_lesson_image.setText(_translate("MainWindow", "ছবি"))
        self.lsn_lbl_lesson_topic.setText(_translate("MainWindow", "পরিচয়"))
        self.lsn_btn_add_lessons.setText(_translate("MainWindow", "নতুন পাঠ যুক্ত করুন"))
        self.lsn_lbl_headline_2.setText(_translate("MainWindow", "পাঠ মূল্যায়ন"))
        self.task_btn_mcq.setText(_translate("MainWindow", "বহুনির্বচনী"))
        self.task_btn_matching.setText(_translate("MainWindow", "শব্দ মিলাই"))
        self.task_btn_sequence.setText(_translate("MainWindow", "ক্রমধারা"))
        self.task_btn_puzzle.setText(_translate("MainWindow", "ধাঁধা"))
        self.task_lbl_mcq.setText(_translate("MainWindow", "বহু নির্বচনী প্রশ্নোত্তর"))
        self.task_lbl_matching.setText(_translate("MainWindow", "শব্দ মিলাই"))
        self.task_lbl_sequencing.setText(_translate("MainWindow", "ক্রমধারা"))
        self.task_lbl_puzzle.setText(_translate("MainWindow", "ধাঁধা"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
