# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Frontend\PyQt_UI\sound_recorder.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_audioRecorderWidget(object):
    def setupUi(self, audioRecorderWidget):
        audioRecorderWidget.setObjectName("audioRecorderWidget")
        audioRecorderWidget.resize(479, 566)
        self.gridLayout = QtWidgets.QGridLayout(audioRecorderWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.audioRecorderFrame = QtWidgets.QFrame(audioRecorderWidget)
        self.audioRecorderFrame.setStyleSheet("background-color: rgb(142, 226, 205)")
        self.audioRecorderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.audioRecorderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.audioRecorderFrame.setObjectName("audioRecorderFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.audioRecorderFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(84, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 2)
        self.soundingButton = QtWidgets.QPushButton(self.audioRecorderFrame)
        self.soundingButton.setMinimumSize(QtCore.QSize(50, 40))
        self.soundingButton.setMaximumSize(QtCore.QSize(50, 40))
        self.soundingButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"}\n"
"")
        self.soundingButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/record_listen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.soundingButton.setIcon(icon)
        self.soundingButton.setIconSize(QtCore.QSize(40, 100))
        self.soundingButton.setObjectName("soundingButton")
        self.gridLayout_2.addWidget(self.soundingButton, 1, 2, 1, 2)
        self.startButton = QtWidgets.QPushButton(self.audioRecorderFrame)
        self.startButton.setMinimumSize(QtCore.QSize(100, 100))
        self.startButton.setMaximumSize(QtCore.QSize(100, 100))
        self.startButton.setStyleSheet("QPushButton {\n"
"    border-radius: 50px;\n"
"    border: 3px solid rgb(206, 95, 95)\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"    background-color:  rgb(255, 131, 139);\n"
"    border-radius: 50px;\n"
"}")
        self.startButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/record_before_start_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon1)
        self.startButton.setIconSize(QtCore.QSize(200, 200))
        self.startButton.setObjectName("startButton")
        self.gridLayout_2.addWidget(self.startButton, 1, 4, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.audioRecorderFrame)
        self.stopButton.setMinimumSize(QtCore.QSize(50, 40))
        self.stopButton.setMaximumSize(QtCore.QSize(50, 40))
        self.stopButton.setStyleSheet("border: none;")
        self.stopButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\Frontend\\PyQt_UI\\../Images/record_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setIconSize(QtCore.QSize(40, 100))
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_2.addWidget(self.stopButton, 1, 5, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 7, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 4, 1, 1)
        self.recordingTime = QtWidgets.QLabel(self.audioRecorderFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.recordingTime.setFont(font)
        self.recordingTime.setStyleSheet("border: 2px solid rgb(0, 43, 91) ;\n"
"border-radius: 15px;\n"
"background-color: rgb(231, 231, 231);")
        self.recordingTime.setAlignment(QtCore.Qt.AlignCenter)
        self.recordingTime.setObjectName("recordingTime")
        self.gridLayout_2.addWidget(self.recordingTime, 3, 2, 1, 5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 4, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(46, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 5, 0, 1, 1)
        self.fileName = QtWidgets.QLineEdit(self.audioRecorderFrame)
        self.fileName.setMinimumSize(QtCore.QSize(330, 50))
        self.fileName.setMaximumSize(QtCore.QSize(330, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fileName.setFont(font)
        self.fileName.setStyleSheet("border: 2px solid rgb(0, 43, 91) ;\n"
"border-radius: 15px;\n"
"background-color: rgb(231, 231, 231);")
        self.fileName.setText("")
        self.fileName.setAlignment(QtCore.Qt.AlignCenter)
        self.fileName.setObjectName("fileName")
        self.gridLayout_2.addWidget(self.fileName, 5, 1, 1, 7)
        spacerItem6 = QtWidgets.QSpacerItem(37, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 5, 8, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 6, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(123, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 7, 0, 1, 3)
        self.saveButton = QtWidgets.QPushButton(self.audioRecorderFrame)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 40))
        self.saveButton.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("border: 2px solid rgb(0, 43, 91) ;\n"
"border-radius: 15px;\n"
"background-color: rgb(36, 105, 127);\n"
"color: rgb(137, 218, 199)")
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_2.addWidget(self.saveButton, 7, 3, 1, 3)
        spacerItem9 = QtWidgets.QSpacerItem(114, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 7, 6, 1, 3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 8, 4, 1, 1)
        self.gridLayout.addWidget(self.audioRecorderFrame, 1, 0, 1, 1)

        self.retranslateUi(audioRecorderWidget)
        QtCore.QMetaObject.connectSlotsByName(audioRecorderWidget)

    def retranslateUi(self, audioRecorderWidget):
        _translate = QtCore.QCoreApplication.translate
        audioRecorderWidget.setWindowTitle(_translate("audioRecorderWidget", "Form"))
        self.recordingTime.setText(_translate("audioRecorderWidget", "সময়..."))
        self.fileName.setPlaceholderText(_translate("audioRecorderWidget", "অডিও ফাইলের নাম লিখুন"))
        self.saveButton.setText(_translate("audioRecorderWidget", "সংরক্ষণ করুন"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    audioRecorderWidget = QtWidgets.QWidget()
    ui = Ui_audioRecorderWidget()
    ui.setupUi(audioRecorderWidget)
    audioRecorderWidget.show()
    sys.exit(app.exec_())
