# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\Teacher_Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainframe = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainframe.sizePolicy().hasHeightForWidth())
        self.mainframe.setSizePolicy(sizePolicy)
        self.mainframe.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mainframe.setStyleSheet("background-color: #FEE8E9;")
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.gridLayout = QtWidgets.QGridLayout(self.mainframe)
        self.gridLayout.setObjectName("gridLayout")
        self.banner_pic_frame = QtWidgets.QFrame(self.mainframe)
        self.banner_pic_frame.setMaximumSize(QtCore.QSize(1200, 300))
        self.banner_pic_frame.setStyleSheet("border: none;")
        self.banner_pic_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.banner_pic_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.banner_pic_frame.setObjectName("banner_pic_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.banner_pic_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.b_picture = QtWidgets.QLabel(self.banner_pic_frame)
        self.b_picture.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.b_picture.setStyleSheet("border: none;")
        self.b_picture.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.b_picture.setText("")
        self.b_picture.setPixmap(QtGui.QPixmap(".\\UI\\final_logo.png"))
        self.b_picture.setScaledContents(False)
        self.b_picture.setAlignment(QtCore.Qt.AlignCenter)
        self.b_picture.setObjectName("b_picture")
        self.verticalLayout.addWidget(self.b_picture)
        self.gridLayout.addWidget(self.banner_pic_frame, 1, 0, 1, 1)
        self.space_frame = QtWidgets.QFrame(self.mainframe)
        self.space_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.space_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.space_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.space_frame.setObjectName("space_frame")
        self.gridLayout.addWidget(self.space_frame, 3, 0, 1, 1)
        self.bnt_lbl_frame = QtWidgets.QFrame(self.mainframe)
        self.bnt_lbl_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.bnt_lbl_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.bnt_lbl_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bnt_lbl_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bnt_lbl_frame.setObjectName("bnt_lbl_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.bnt_lbl_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_student = QtWidgets.QLabel(self.bnt_lbl_frame)
        self.lbl_student.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_student.setFont(font)
        self.lbl_student.setStyleSheet("color: rgb(129, 102, 106);")
        self.lbl_student.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_student.setObjectName("lbl_student")
        self.horizontalLayout_3.addWidget(self.lbl_student)
        self.lbl_lesson = QtWidgets.QLabel(self.bnt_lbl_frame)
        self.lbl_lesson.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_lesson.setFont(font)
        self.lbl_lesson.setStyleSheet("color: rgb(129, 102, 106);")
        self.lbl_lesson.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_lesson.setObjectName("lbl_lesson")
        self.horizontalLayout_3.addWidget(self.lbl_lesson)
        self.lbl_quiz = QtWidgets.QLabel(self.bnt_lbl_frame)
        self.lbl_quiz.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_quiz.setFont(font)
        self.lbl_quiz.setStyleSheet("color: rgb(129, 102, 106);")
        self.lbl_quiz.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_quiz.setObjectName("lbl_quiz")
        self.horizontalLayout_3.addWidget(self.lbl_quiz)
        self.lbl_progress = QtWidgets.QLabel(self.bnt_lbl_frame)
        self.lbl_progress.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_progress.setFont(font)
        self.lbl_progress.setStyleSheet("color: rgb(129, 102, 106);")
        self.lbl_progress.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_progress.setObjectName("lbl_progress")
        self.horizontalLayout_3.addWidget(self.lbl_progress)
        self.lbl_settings = QtWidgets.QLabel(self.bnt_lbl_frame)
        self.lbl_settings.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_settings.setFont(font)
        self.lbl_settings.setStyleSheet("color: rgb(129, 102, 106);")
        self.lbl_settings.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_settings.setObjectName("lbl_settings")
        self.horizontalLayout_3.addWidget(self.lbl_settings)
        self.gridLayout.addWidget(self.bnt_lbl_frame, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 1)
        self.btn_frame = QtWidgets.QFrame(self.mainframe)
        self.btn_frame.setMinimumSize(QtCore.QSize(0, 190))
        self.btn_frame.setMaximumSize(QtCore.QSize(1270, 190))
        self.btn_frame.setStyleSheet("")
        self.btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_frame.setObjectName("btn_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.btn_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_student = QtWidgets.QPushButton(self.btn_frame)
        self.btn_student.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_student.setFont(font)
        self.btn_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_student.setMouseTracking(True)
        self.btn_student.setAcceptDrops(True)
        self.btn_student.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(227, 208, 209, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 5px solid rgb(238, 218, 219);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"     border: 5px solid  rgb(148, 122, 125);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.318, x2:0, y2:1, stop:0.313433 rgba(222, 204, 205, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"")
        self.btn_student.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\UI\\icons8_student_male_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_student.setIcon(icon)
        self.btn_student.setIconSize(QtCore.QSize(500, 500))
        self.btn_student.setFlat(False)
        self.btn_student.setObjectName("btn_student")
        self.horizontalLayout_2.addWidget(self.btn_student)
        self.btn_lesson = QtWidgets.QPushButton(self.btn_frame)
        self.btn_lesson.setMaximumSize(QtCore.QSize(200, 200))
        self.btn_lesson.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_lesson.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(227, 208, 209, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 5px solid rgb(238, 218, 219);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"     border: 5px solid  rgb(148, 122, 125);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.318, x2:0, y2:1, stop:0.313433 rgba(222, 204, 205, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.btn_lesson.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\UI\\lesson_64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_lesson.setIcon(icon1)
        self.btn_lesson.setIconSize(QtCore.QSize(150, 150))
        self.btn_lesson.setObjectName("btn_lesson")
        self.horizontalLayout_2.addWidget(self.btn_lesson)
        self.btn_quiz = QtWidgets.QPushButton(self.btn_frame)
        self.btn_quiz.setMaximumSize(QtCore.QSize(200, 200))
        self.btn_quiz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_quiz.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(227, 208, 209, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 5px solid rgb(238, 218, 219);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"     border: 5px solid  rgb(148, 122, 125);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.318, x2:0, y2:1, stop:0.313433 rgba(222, 204, 205, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.btn_quiz.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\UI\\list_64px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_quiz.setIcon(icon2)
        self.btn_quiz.setIconSize(QtCore.QSize(150, 150))
        self.btn_quiz.setObjectName("btn_quiz")
        self.horizontalLayout_2.addWidget(self.btn_quiz)
        self.btn_progress = QtWidgets.QPushButton(self.btn_frame)
        self.btn_progress.setMaximumSize(QtCore.QSize(200, 200))
        self.btn_progress.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_progress.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(227, 208, 209, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 5px solid rgb(238, 218, 219);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"     border: 5px solid  rgb(148, 122, 125);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.318, x2:0, y2:1, stop:0.313433 rgba(222, 204, 205, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.btn_progress.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\UI\\presentation_64px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_progress.setIcon(icon3)
        self.btn_progress.setIconSize(QtCore.QSize(150, 150))
        self.btn_progress.setObjectName("btn_progress")
        self.horizontalLayout_2.addWidget(self.btn_progress)
        self.btn_settings = QtWidgets.QPushButton(self.btn_frame)
        self.btn_settings.setMaximumSize(QtCore.QSize(200, 200))
        self.btn_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_settings.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(227, 208, 209, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 5px solid rgb(238, 218, 219);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"     border: 5px solid  rgb(148, 122, 125);\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.318, x2:0, y2:1, stop:0.313433 rgba(222, 204, 205, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.btn_settings.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\UI\\settings_64px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon4)
        self.btn_settings.setIconSize(QtCore.QSize(150, 150))
        self.btn_settings.setObjectName("btn_settings")
        self.horizontalLayout_2.addWidget(self.btn_settings)
        self.gridLayout.addWidget(self.btn_frame, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.mainframe, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_student.setText(_translate("MainWindow", "শিক্ষার্থী নিবন্ধন"))
        self.lbl_lesson.setText(_translate("MainWindow", "পাঠ্যসূচী"))
        self.lbl_quiz.setText(_translate("MainWindow", "পাঠ মূল্যায়ন"))
        self.lbl_progress.setText(_translate("MainWindow", "শিক্ষার্থীর পারফরম্যান্স"))
        self.lbl_settings.setText(_translate("MainWindow", "সেটিংস"))

